/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-25 02:52:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xietong.software.sdtw.club.ClubUtil;
import com.xietong.software.sdtw.db.ClubMembers;
import com.xietong.software.common.COptionConst;
import com.xietong.software.base.Power;
import com.xietong.software.sdtw.db.BaseUserCode;
import com.xietong.software.base.SdtwConst;
import com.xietong.software.sdtw.db.ClientAttach;
import com.xietong.software.common.HeadConst;
import com.xietong.software.sdtw.db.Students;
import com.xietong.software.sdtw.db.Club;
import com.xietong.software.util.ParamUtils;
import com.xietong.software.util.Tool;
import com.xietong.software.common.UserInfo;
import com.xietong.software.common.CEditConst;
import com.xietong.software.common.HtmlTool;
import java.util.*;

public final class club_002dsetup_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/student/pagetop-positionandhelp.jsp", Long.valueOf(1493084791070L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//社团申请页面 
      out.write('\r');
      out.write('\n');

UserInfo userInfo = Tool.getUserInfo(request);
if(!userInfo.hasFunPower(Power.USERSTUDENTPOWER)){
	out.print(HtmlTool.msgBox(request, "请先登录","../index.jsp","../index.jsp"));
	return;
}
List OrgCityNameOptions = CEditConst.getOrgCityNameOptions(userInfo,"");
List ClubTypeNameOptions = CEditConst.getClubTypeNameOptions(userInfo,"");
List AcademyNameOptions = CEditConst.getAcademyNameOptions(userInfo,"");
int id = ParamUtils.getIntParameter(request,"id",-1);
Club club = new Club();
if(id!=-1&&club.getById(id)!=null){
	club = club.getById(id);
}
String cmd = ParamUtils.getParameter(request,"cmd","");
String backurl = ParamUtils.getParameter(request,"backurl","");
String active = ParamUtils.getParameter(request,"active","0");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link href=\"../css/common-student.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../js/tablelist.js\"></script>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/autosearch.css\"> -->\r\n");
      out.write("<script src=\"../js/autosearch.js\"></script>\r\n");
      out.write("<script src=\"../main/js/common.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"../main/js/ajaxfileupload.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".blocktitle{\r\n");
      out.write("\tfont-size:large;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("checkSubmitFlg = false; \r\n");
      out.write("function formsubmit(){\r\n");
      out.write("\tvar City = $('#City').val();\r\n");
      out.write("\tvar ClubName = $('#ClubName').val();\r\n");
      out.write("\tvar ClubType = $('#ClubType').val();\r\n");
      out.write("\tvar Chairman = $('#Chairman').val();\r\n");
      out.write("\tvar Academy = $('#Academy').val();\r\n");
      out.write("\t//var Teacher = $('#Teacher').val();\r\n");
      out.write("\tvar Clubqq = $('#Clubqq').val();\r\n");
      out.write("\tvar ClubeMail = $('#ClubeMail').val();\r\n");
      out.write("\tvar ClubPubAccount = $('#ClubPubAccount').val();\r\n");
      out.write("\tvar Tenet = $('#Tenet').val();\r\n");
      out.write("\tvar ClubProfile = $('#ClubProfile').val();\r\n");
      out.write("\tvar Sponsor = $('#SId').val();\r\n");
      out.write("\tif(City==\"\"||City==\"-1\"){\r\n");
      out.write("\t\t$('#City').focus();\r\n");
      out.write("\t\talert(\"请选择所在校区城市！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write(" \tif(ClubName==\"\"){\r\n");
      out.write("\t\t$('#ClubName').focus();\r\n");
      out.write("\t\talert(\"请录入社团名称！\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write(" \t if(ClubType==\"\"||ClubType==\"-1\"){\r\n");
      out.write("\t\t$('#ClubType').focus();\r\n");
      out.write("\t\talert(\"请选择社团类别！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write(" \tif(Chairman==\"\"){\r\n");
      out.write("\t\t$('#Chairman').focus();\r\n");
      out.write("\t\talert(\"请录入拟任负责人！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write(" \tif(Academy==\"\"||Academy==\"-1\"){\r\n");
      out.write("\t\t$('#Academy').focus();\r\n");
      out.write("\t\talert(\"请选择指导单位！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* if(Teacher==\"\"){\r\n");
      out.write("\t\t$('#Teacher').focus();\r\n");
      out.write("\t\talert(\"请录入指导老师\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} */\r\n");
      out.write("\tif(Clubqq==\"\"){\r\n");
      out.write("\t\t$('#Clubqq').focus();\r\n");
      out.write("\t\talert(\"请录入QQ！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(ClubeMail==\"\"){\r\n");
      out.write("\t\t$('#ClubeMail').focus();\r\n");
      out.write("\t\talert(\"请录入邮箱！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar myreg = /^([a-zA-Z0-9]+[_|\\_|\\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\\_|\\.]?)*[a-zA-Z0-9]+\\.[a-zA-Z]{2,3}$/;\r\n");
      out.write("    if(!myreg.test(ClubeMail)){\r\n");
      out.write("    \t$('#ClubeMail').focus();\r\n");
      out.write("    \talert(\"邮箱格式不正确！\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("\t }\r\n");
      out.write("    if(ClubPubAccount==\"\"){\r\n");
      out.write("    \t$('#ClubPubAccount').focus();\r\n");
      out.write("    \talert(\"请录入公众号！\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }\r\n");
      out.write("    if(Tenet==\"\"){\r\n");
      out.write("    \t$(\"#Tenet\").focus();\r\n");
      out.write("    \talert(\"请录入社团宗旨！\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }\r\n");
      out.write("    if(ClubProfile==\"\"){\r\n");
      out.write("    \t$('#ClubProfile').focus();\r\n");
      out.write("    \talert(\"请录入社团简介！\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }\r\n");
      out.write("    /* if(Sponsor==\"\"){\r\n");
      out.write("    \talert(\"请添加发起人情况!\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    } */\r\n");
      out.write("    var SId = $('#SId').val();\r\n");
      out.write("\tvar Nums = $('#Nums').val();\r\n");
      out.write("\tif (SId==\"\"&&Nums==\"\") {\r\n");
      out.write("\t\talert(\"设置 发起人情况信息\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif(chekSname('SName')||chekSname('teamtable')){\r\n");
      out.write("\t\tif(checkSubmitFlg ==true){\r\n");
      out.write("\t\t\talert(\"请勿重复提交!\");\r\n");
      out.write("\t\t\treturn; //当表单被提交过一次后checkSubmitFlg将变为true,根据判断将无法进行提交。 \r\n");
      out.write("\t\t} \r\n");
      out.write("\t\tcheckSubmitFlg = true; \r\n");
      out.write("\t\t$('#postForm').submit();\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\talert(\" 发起人情况信息不能为空！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function chekSname(id) {\r\n");
      out.write("\tvar f = true;\r\n");
      out.write("\t$(\"#\"+id).find(\"input\").each(function () {\r\n");
      out.write("        if ($(this).val() == \"\") {\r\n");
      out.write("        \t//alert($(this).attr(\"id\"))\r\n");
      out.write("            $(this).focus();\r\n");
      out.write("            f=false;\r\n");
      out.write("        }else{\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    return f;\r\n");
      out.write("}\r\n");
      out.write("function formcancel(backurl){\r\n");
      out.write("\tlocation.href=backurl;\r\n");
      out.write("}\r\n");
      out.write("function addSponsor(){\r\n");
      out.write("\topenWindow(\"BaseUserCodeAction.jsp?values=\"+$(\"#SId\").val(),\"703,400\");\r\n");
      out.write("}\r\n");
      out.write("function addSponsorN(){\r\n");
      out.write("\topenWindow(\"BaseUserCodeAction.jsp?cmd=nfzr&values=\"+$(\"#Chairman\").val(),\"703,400\");\r\n");
      out.write("}\r\n");
      out.write("function setRole(pName,pId){\r\n");
      out.write("\t$(\"#SName\").append(pName);\r\n");
      out.write("\t$(\"#SId\").val(pId);\r\n");
      out.write("}\r\n");
      out.write("function setRoleN(pName,pId){\r\n");
      out.write("\t//alert(pName+\"   \"+pId)\r\n");
      out.write("\t$(\"#ChairmanName\").val(pName);\r\n");
      out.write("\t$(\"#Chairman\").val(pId);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function uploadOtherAttatch(){//上传其他附件\r\n");
      out.write("\t//debugger;\r\n");
      out.write("\tvar name=document.getElementById('OtherAttach').value;\r\n");
      out.write("    $(\"#load1\")\r\n");
      out.write("    .ajaxStart(function(){\r\n");
      out.write("        $(this).show();\r\n");
      out.write("    })\r\n");
      out.write("    .ajaxComplete(function(){\r\n");
      out.write("        $(this).hide();\r\n");
      out.write("    });\r\n");
      out.write("    $.ajaxFileUpload\r\n");
      out.write("    (\r\n");
      out.write("        {\r\n");
      out.write("            url:'club-setup-addsave.jsp?cmd=otherattach',\r\n");
      out.write("            secureuri:false,\r\n");
      out.write("            fileElementId:'OtherAttach',\r\n");
      out.write("            type:'post',\t\r\n");
      out.write("            dataType: 'json',\r\n");
      out.write("            success: function (data, status)\r\n");
      out.write("            {\r\n");
      out.write("                if(typeof(data.error) != 'undefined')\r\n");
      out.write("                {\r\n");
      out.write("                    if(data.error != '')\r\n");
      out.write("                    {                    \r\n");
      out.write("                        alert(data.error);\r\n");
      out.write("                    }else\r\n");
      out.write("                    {\r\n");
      out.write("                    \t// if(document.postForm.AddFileList.value==\"\"){\r\n");
      out.write("                         \tvar be = data.url.indexOf(\"=\");\r\n");
      out.write("                         \tvar en = data.url.lastIndexOf(\"/\");\r\n");
      out.write("                         \tdocument.postForm.AddFileList.value = data.ids;\r\n");
      out.write("                        /*  }else{\r\n");
      out.write("                         \tvar be = data.url.indexOf(\"=\");\r\n");
      out.write("                         \tvar en = data.url.lastIndexOf(\"/\");\r\n");
      out.write("                         \tdocument.postForm.AddFileList.value += \",\"+data.ids;\r\n");
      out.write("                         }  */\r\n");
      out.write("                        var table = document.getElementById('ShowFiles');\r\n");
      out.write("                        var num = table.rows.length;\r\n");
      out.write("                        var row = table.insertRow(num);\r\n");
      out.write("                        var filename = data.url.replace(/.*(\\/|\\\\)/, \"\");\r\n");
      out.write("                        filename = data.name;\r\n");
      out.write("                        var cell = row.insertCell(0);\r\n");
      out.write("                        ");

                        	if(cmd.equals("update")){
                        
      out.write("\r\n");
      out.write("\t\t                        row.id = data.ids;//修改时以防和之前重名\r\n");
      out.write("\t\t                        cell.innerHTML =  '<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/file1.gif\\'/> '+filename+'&nbsp;&nbsp;&nbsp;&nbsp;<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/delete.gif\\' alt=\\'删除\\' title=\\'删除\\' onclick=\\'deleteUpdateFile(\"'+filename+'\",'+data.ids+');\\' style=\"cursor:point;\"/>';\r\n");
      out.write("                        ");

                        	}else{
                        
      out.write("\r\n");
      out.write("\t\t                        row.id = data.ids;//修改时以防和之前重名\r\n");
      out.write("\t\t                        cell.innerHTML =  '<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/file1.gif\\'/> '+filename+'&nbsp;&nbsp;&nbsp;&nbsp;<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/delete.gif\\' alt=\\'删除\\' title=\\'删除\\' onclick=\\'deleteUpdateFile(\"'+filename+'\",'+data.ids+');\\' style=\"cursor:point;\"/>';\r\n");
      out.write("                        ");

                        	}
                        
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function (data, status, e)\r\n");
      out.write("            {\r\n");
      out.write("                alert(\"上传文件失败，请重新上传！\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    )\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("上传文档格式过滤\r\n");
      out.write("*/\r\n");
      out.write("function checkFileType(){//上传文档格式过滤\r\n");
      out.write("\tvar file=document.getElementById('OtherAttach').value;\r\n");
      out.write("\tif(file){\r\n");
      out.write("\t\tvar allowType = {\"doc\":\"\", \"xls\":\"\", \"docx\":\"\", \"xlsx\":\"\"};\r\n");
      out.write("\t\tvar filename=file.replace(/.*(\\/|\\\\)/, \"\");//jquery获得文件名\r\n");
      out.write("\t\tvar fileExt=(/[.]/.exec(filename)) ? /[^.]+$/.exec(filename.toLowerCase()) : '';//jquery获得后缀名\r\n");
      out.write("\t\tif((fileExt+\"\").toLowerCase() in allowType){\r\n");
      out.write("\t\t\tuploadOtherAttatch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\talert(\"上传文件格式不符合要求，请重新选择！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function deleteUpdateFile(name,id){//删除修改时上传附件\r\n");
      out.write("\tif(confirm('是否确定删除？')){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\t\t\t\r\n");
      out.write("\t\t\turl:\"club-setup-addsave.jsp?cmd=delAttach&did=\"+id,\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tbeforeSend:function(){\r\n");
      out.write("\t\t\t\t$(\"#load1\").show();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(data, status, e){\r\n");
      out.write("\t        \tif(typeof(data.error) != 'undefined'){\r\n");
      out.write("                    if(data.error != '')\r\n");
      out.write("                    {\r\n");
      out.write("                        alert(data.error);\r\n");
      out.write("                    }else\r\n");
      out.write("                    {\r\n");
      out.write("                    \t$(\"#load1\").hide();\r\n");
      out.write("        \t\t\t\tvar row = document.getElementById(id);\r\n");
      out.write("        \t\t\t\tfor(var i=0;i<row.cells.length;i++){\r\n");
      out.write("        \t\t\t\t\trow.deleteCell(i);\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t\tvar files = document.postForm.AddFileList.value;\r\n");
      out.write("        \t\t\t\t//alert(files+\" \"+id+\" \"+files.indexOf(id))\r\n");
      out.write("        \t\t\t\tif(files.indexOf(id)!=-1){\r\n");
      out.write("        \t\t\t\t\t//替换删掉的附件id\r\n");
      out.write("        \t\t\t\t\tfiles = \",\"+files+\",\";\r\n");
      out.write("        \t\t\t\t\tfiles = files.replace(\",\"+id+\",\",',');\r\n");
      out.write("        \t\t\t\t\t//没有附件的情况\r\n");
      out.write("        \t\t\t\t\tif(files.indexOf(\",\")==files.lastIndexOf(\",\"))\r\n");
      out.write("        \t\t\t\t\t\tfiles = \"\";\r\n");
      out.write("        \t\t\t\t\telse{\r\n");
      out.write("        \t\t\t\t\t\tfiles = files.substring(1,files.length-1);\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\tdocument.postForm.AddFileList.value = files;\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("             },\r\n");
      out.write("            error: function (data, status, e){\r\n");
      out.write("            \t$(\"#load1\").hide();\r\n");
      out.write("                alert(\"删除文件失败!\");\r\n");
      out.write("            }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function deleteSponsor(trid,id){\r\n");
      out.write("\t$('#'+trid).remove();\r\n");
      out.write("\tvar files = document.postForm.SId.value;\r\n");
      out.write("\t//alert(files+\" \"+id+\" \"+files.indexOf(id))\r\n");
      out.write("\tif(files.indexOf(id)!=-1){\r\n");
      out.write("\t\t//替换删掉的附件id\r\n");
      out.write("\t\tfiles = \",\"+files+\",\";\r\n");
      out.write("\t\tfiles = files.replace(\",\"+id+\",\",',');\r\n");
      out.write("\t\t//没有附件的情况\r\n");
      out.write("\t\tif(files.indexOf(\",\")==files.lastIndexOf(\",\"))\r\n");
      out.write("\t\t\tfiles = \"\";\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tfiles = files.substring(1,files.length-1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.postForm.SId.value = files;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("/* $(function(){\r\n");
      out.write("\t$(\"#Chairman\").chosen({width:'150px;',placeholder_text_single:'请选择 ',no_results_text:\"没有找到\"});\r\n");
      out.write("\t//$(\"#Teacher\").chosen({width:'150px;',placeholder_text_single:'请选择 ',no_results_text:\"没有找到\"});\r\n");
      out.write("\t$(\"#Academy\").chosen({width:'150px;',placeholder_text_single:'请选择 ',no_results_text:\"没有找到\"});\r\n");
      out.write("}) */\r\n");
      out.write("function addMember(){\r\n");
      out.write("\topenWindow(\"BaseUserCodeAction.jsp?values=\"+$(\"#SId\").val(),\"703,400\");\r\n");
      out.write("}\r\n");
      out.write("function setRole(pName,pId){\r\n");
      out.write("\t$(\"#SName\").append(pName);\r\n");
      out.write("\t$(\"#SId\").val(pId);\r\n");
      out.write("}\r\n");
      out.write("function getoptions(cmd){\r\n");
      out.write("\tvar options = \"\";\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("        url: \"club-setup-addsave.jsp\",\r\n");
      out.write("        async:false,\r\n");
      out.write("       data: {cmd:cmd},\r\n");
      out.write("        dataType: \"html\",\r\n");
      out.write("        cache: false,\r\n");
      out.write("        success: function(data){\r\n");
      out.write("        \toptions = data;\r\n");
      out.write("                 },\r\n");
      out.write("                 error : function() { \r\n");
      out.write("                             // view(\"异常！\"); \r\n");
      out.write("                             alert( \"异常！\"); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    });\r\n");
      out.write("\treturn options;\r\n");
      out.write("}\r\n");
      out.write("//研究生添加\r\n");
      out.write("function addItem(){\r\n");
      out.write("\tvar AcademyOptions = getoptions(\"AcademyOptions\");\r\n");
      out.write("\tvar GradeOptions = getoptions(\"GradeOptions\");\r\n");
      out.write("\tvar sexOptions = \"<option value=-1></option><option value=0>男</option><option value=1>女</option>\";\r\n");
      out.write("\tvar dutyOptions = \"<option value=-1></option><option value=1>团支书</option><option value=2>财务负责人</option><option value=3>其他</option>\";\r\n");
      out.write("\tvar rowspan = document.getElementById(\"teamtable\").rows.length;\r\n");
      out.write("\tif (rowspan==1) {\r\n");
      out.write("\t\t$('#Nums').val(rowspan);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\t$('#Nums').val($('#Nums').val()+\",\"+rowspan);\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#teamtable\").append(\r\n");
      out.write("/* \t\"<tr id=del\"+rowspan+\" class=odd>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'> <input id='MemberSno_t\"+rowspan+\"' size='15' name='MemberSno_t\"+rowspan+\"' style='width: 80%'/></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><input  id='MemberName_t\"+rowspan+\"'size='15' name='MemberName_t\"+rowspan+\"' style='width: 80%'/></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select id='MemberSex_t\"+rowspan+\"' name='MemberSex_t\"+rowspan+\"'>\"+sexOptions+\"</select></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select style='width:100%;' id='MemberAcademy_t\"+rowspan+\"' name='MemberAcademy_t\"+rowspan+\"'>\"+AcademyOptions+\"</select></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><input  id='Identity_t\"+rowspan+\"'size='15' name='Identity_t\"+rowspan+\"' style='width: 80%' value='1' type='hidden'/>研究生</td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select id='MemberGrade_t\"+rowspan+\"' name='MemberGrade_t\"+rowspan+\"'>\"+GradeOptions+\"</select></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><input  id='MemberPhone_t\"+rowspan+\"'size='15' name='MemberPhone_t\"+rowspan+\"' style='width: 80%'/></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select id='MemberDuty_t\"+rowspan+\"' name='MemberDuty_t\"+rowspan+\"'>\"+dutyOptions+\"</select></td>\"+\t\r\n");
      out.write("\t\t\"<td style='width:10%;'><img  style='cursor:point;' src='../main/images/delete.gif' onclick=javascript:deleteSponsor2('del\"+rowspan+\"',\"+rowspan+\") alt=删除  title=删除  border=0></td>\"+\t\r\n");
      out.write("\t\"</tr>\"\r\n");
      out.write("\t */\r\n");
      out.write("\t\t\"<tr id=del\"+rowspan+\" class=odd>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'> <input type='text' id='Sno_t\"+rowspan+\"' size='15' name='Sno_t\"+rowspan+\"' style='width: 80%'/></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><input type='text' id='SName_t\"+rowspan+\"'size='15' name='SName_t\"+rowspan+\"' style='width: 80%'/></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select id='Sex_t\"+rowspan+\"' name='Sex_t\"+rowspan+\"'>\"+sexOptions+\"</select></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select style='width:100%;' id='Academy_t\"+rowspan+\"' name='Academy_t\"+rowspan+\"'>\"+AcademyOptions+\"</select></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><input  id='Identity_t\"+rowspan+\"'size='15' name='Identity_t\"+rowspan+\"' style='width: 80%' value='1' type='hidden'/>研究生</td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select id='Grade_t\"+rowspan+\"' name='Grade_t\"+rowspan+\"'>\"+GradeOptions+\"</select></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><input type='text' id='Phone_t\"+rowspan+\"'size='15' name='Phone_t\"+rowspan+\"' style='width: 80%'/></td>\"+\r\n");
      out.write("\t\t\"<td style='width:10%;'><select id='Duty_t\"+rowspan+\"' name='Duty_t\"+rowspan+\"'>\"+dutyOptions+\"</select></td>\"+\t\r\n");
      out.write("\t\t\"<td style='width:10%;'><img  style='cursor:point;' src='../main/images/delete.gif' onclick=javascript:deleteSponsor2('del\"+rowspan+\"',\"+rowspan+\") alt=删除  title=删除  border=0></td>\"+\t\r\n");
      out.write("\t\"</tr>\"\r\n");
      out.write("\t);\r\n");
      out.write("}\r\n");
      out.write("function deleteSponsor2(trid,id){\r\n");
      out.write("\t$('#'+trid).remove();\r\n");
      out.write("\tvar files = $('#Nums').val();\r\n");
      out.write("\t//alert(files+\" \"+id+\" \"+files.indexOf(id))\r\n");
      out.write("\tif(files.indexOf(id)!=-1){\r\n");
      out.write("\t\t//替换删掉的附件id\r\n");
      out.write("\t\tfiles = \",\"+files+\",\";\r\n");
      out.write("\t\tfiles = files.replace(\",\"+id+\",\",',');\r\n");
      out.write("\t\t//没有附件的情况\r\n");
      out.write("\t\tif(files.indexOf(\",\")==files.lastIndexOf(\",\"))\r\n");
      out.write("\t\t\tfiles = \"\";\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tfiles = files.substring(1,files.length-1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//document.postForm.SId.value = files;\r\n");
      out.write("\t\t$('#Nums').val(files);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function deleteSponsor(trid,id){\r\n");
      out.write("\t$('#'+trid).remove();\r\n");
      out.write("\tvar files = $('#SId').val();\r\n");
      out.write("\t//alert(files+\" \"+id+\" \"+files.indexOf(id))\r\n");
      out.write("\tif(files.indexOf(id)!=-1){\r\n");
      out.write("\t\t//替换删掉的附件id\r\n");
      out.write("\t\tfiles = \",\"+files+\",\";\r\n");
      out.write("\t\tfiles = files.replace(\",\"+id+\",\",',');\r\n");
      out.write("\t\t//没有附件的情况\r\n");
      out.write("\t\tif(files.indexOf(\",\")==files.lastIndexOf(\",\"))\r\n");
      out.write("\t\t\tfiles = \"\";\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tfiles = files.substring(1,files.length-1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//document.postForm.SId.value = files;\r\n");
      out.write("\t\t$('#SId').val(files);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

String strposition = "学生社团工作 >> 社团成立申请 >> ";
String strfunction = "添加社团成立申请";
String strhelpwords = "提交社团成立申请。";
if("view".equals(cmd)||"viewlist".equals(cmd)){
	strfunction = "查看社团成立申请";
	strhelpwords = "查看社团成立申请。";
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"location-table\" >\r\n");
      out.write("<tr height=\"35\">\r\n");
      out.write("\t<td class=\"location-title\" >您的位置：");
      out.print(strposition );
      out.write("\r\n");
      out.write("\t\t<span style=\"cursor:pointer;\" onclick=\"showorhide_div('helpdiv')\">");
      out.print(strfunction );
      out.write("</span>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div id=\"helpdiv\" style=\"display:none;width:89%;margin:0 auto;\">\r\n");
      out.write("<table \tclass=\"location-help\"  cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("\t<td align=\"left\">系统帮助：</td>\r\n");
      out.write("   \t<td width=\"30\"> \r\n");
      out.write("\t\t<a align=\"right\" href=\"#\" onclick=\"showorhide_div('helpdiv')\"><font face='Webdings' color='#FF0000' style='font- size:32pt'>×</font></a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("\t<td align=\"left\">");
      out.print(strhelpwords );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function showorhide_div(menu){\r\n");
      out.write("    $(\"#\"+menu).toggle();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"command-table\">\r\n");
      out.write("<tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <a href=\"#\" onclick=\"formcancel('");
      out.print(backurl+"?active="+active);
      out.write("')\" >\r\n");
      out.write("    <!-- <img src=\"../images/commandico/back.png\"> -->返回</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<form name=\"postForm\" id=\"postForm\" action=\"club-setup-addsave.jsp\">\r\n");
      out.write("<table class=\"content-table\">\r\n");
      out.write("<input id=\"cmd\" name=\"cmd\" value=\"");
      out.print(club.getId()==-1?"save":"update");
      out.write("\" type=\"hidden\"/>\r\n");
      out.write("<tr height=\"35\"><td colspan=\"8\" class=\"blocktitle\">基本事项</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\" width=\"15%\">&nbsp;<font color=\"red\">*&nbsp;</font>所在校区城市：</td>\r\n");
      out.write("    <td align=\"left\" >\r\n");
      out.write("\t\t");
      out.print(HtmlTool.renderSelect(OrgCityNameOptions, ""+club.getCity(), "City", ""+userInfo.getOrgId()));
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>指导单位：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\">\r\n");
      out.write("       \t");
      out.print(HtmlTool.renderSelect(AcademyNameOptions, ""+club.getAcademy(), "Academy", ""+userInfo.getDeptId()));
      out.write("\t\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\" width=\"15%\">&nbsp;<font color=\"red\">*&nbsp;</font>社团名称：</td>\r\n");
      out.write("    <td align=\"left\" width=\"35%\"><input type=\"text\" id=\"ClubName\"name=\"ClubName\"  maxlength=\"45\" size=\"30\" value=\"");
      out.print(club.getClubName());
      out.write("\"></td>\r\n");
      out.write("    <td  align=\"right\">&nbsp;社团代码（活动许可代码）：</td>\r\n");
      out.write("     <td align=\"left\">\r\n");
      out.write("     ");
if(SdtwConst.CHECKFLAG_XXTG.equals(club.getCheckFlag())){
      out.write("\r\n");
      out.write("    \t ");
      out.print(club.getClubId() );
      out.write("\r\n");
      out.write("     ");
}else{
      out.write("\r\n");
      out.write("    \t社团申请通过后生成 \r\n");
      out.write("     ");
}
     
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td  align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>社团类别：</td>\r\n");
      out.write("\t<td align=\"left\">\r\n");
      out.write("\t\t<!-- <select name=\"clubtype\" style=\"width:280px;\">\r\n");
      out.write("\t\t\t<option value='理论学习' selected>理论学习</option>\r\n");
      out.write("\t\t\t<option value='公益服务'>公益服务</option>\r\n");
      out.write("\t\t\t<option value='应用实践'>应用实践</option>\r\n");
      out.write("\t\t\t<option value='体育锻炼'>体育锻炼</option>\r\n");
      out.write("\t\t\t<option value='文艺娱乐'>文艺娱乐</option>\r\n");
      out.write("\t\t\t<option value='职业发展'>职业发展</option>\r\n");
      out.write("\t\t\t<option value='其他'>其他</option>\r\n");
      out.write("\t\t</select> -->\r\n");
      out.write("\t\t");
      out.print(HtmlTool.renderSelect(ClubTypeNameOptions, ""+club.getClubType(), "ClubType", "-1"));
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>拟任负责人：</td>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("    ");

    String name = "";
    if(!"".equals(club.getChairman())) {
    	BaseUserCode u = new BaseUserCode();
   		List cdt = new ArrayList();
   		List list = new ArrayList();
   		cdt.add("id ="+club.getChairman());
   		list = u.query(cdt);
   		if(list.size()>0)
   		u = (BaseUserCode)list.get(0);
   		name = u.getCnName();
    }
    
      out.write("\r\n");
      out.write("    ");
//=HtmlTool.renderSelect(UserCnNameOptions,""+club.getChairman(), "Chairman", "-1")
      out.write("\r\n");
      out.write("    <input id=\"Chairman\" name=\"Chairman\" value=\"");
      out.print(club.getChairman());
      out.write("\" type=\"hidden\"/>\r\n");
      out.write("    ");

    
      out.write("\r\n");
      out.write("    <input id=\"ChairmanName\" name=\"ChairmanName\" value=\"");
      out.print(name);
      out.write("\" readonly=\"readonly\"/>\r\n");
      out.write("    <a href=\"#\" class='add_btn' onclick=\"addSponsorN();\">添加</a>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">&nbsp;成立时间：</td>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("    ");
if(SdtwConst.CHECKFLAG_XXTG.equals(club.getCheckFlag())){
      out.write("\r\n");
      out.write("    \t");
      out.print(club.getClubTimeSetup() );
      out.write("\r\n");
      out.write("    ");
}else{
      out.write("\r\n");
      out.write("    \t申请审批通过后设置\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("    <td  align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>QQ：</td>\r\n");
      out.write("     <td align=\"left\"><input type=\"text\" name=\"Clubqq\" id=\"Clubqq\" maxlength=\"45\" size=\"40\" value=\"");
      out.print(club.getClubqq());
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("    <td  align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>Email：</td>\r\n");
      out.write("     <td align=\"left\"><input type=\"text\" name=\"ClubeMail\" id=\"ClubeMail\"  maxlength=\"45\" size=\"40\" value=\"");
      out.print(club.getClubeMail());
      out.write("\"></td>\r\n");
      out.write("    <td  align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>公众号：</td>\r\n");
      out.write("     <td align=\"left\"><input type=\"text\" name=\"ClubPubAccount\" id=\"ClubPubAccount\" maxlength=\"45\" size=\"40\" value=\"");
      out.print(club.getClubPubAccount());
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>社团宗旨：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\"><input type=\"text\" name=\"Tenet\" id=\"Tenet\"  maxlength=\"50\" size=\"80\" value=\"");
      out.print(club.getTenet());
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>社团简介：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\"><textarea name=\"ClubProfile\" id=\"ClubProfile\" cols=\"80%\" rows=\"5\" maxlength=\"2000\">");
      out.print(club.getClubProfile() );
      out.write("</textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"35\"><td colspan=\"4\" align=\"center\" colspan=\"8\" class=\"blocktitle\">相关情况</td></tr>\r\n");
      out.write("<tr height=\"35\"><td colspan=\"4\" align=\"center\" colspan=\"8\" style=\"color: red;\">发起人不少于10人</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">发起人情况\r\n");
      out.write("\t</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\">\r\n");
      out.write("    <table    style=\"border-collapse: separate;border-spacing: 1px;width:100%;font-size:12px;text-align:center;\" cellpadding=\"1px;\" cellspacing=\"1px;\">\r\n");
      out.write("    ");

    ClubUtil util = new ClubUtil();
    List TeamList = util.getTeamList(club.getId(),"1");
    
      out.write("\r\n");
      out.write("\t\t<tr style=\"background-color:#f7f9fc;\">\r\n");
      out.write("\t\t\t<td ><a href=\"#\" onclick=\"addItem();return false;\" style=\"color: red;\">研究生添加</a></td>\r\n");
      out.write("\t\t\t<td colspan=\"8\"><a href=\"#\" class='add_btn' onclick=\"addMember();\">本科生添加</a></td>\r\n");
      out.write("\t\t</tr> \r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<!-- 研究生添加 -->\r\n");
      out.write("    <table id=\"teamtable\" style=\"border-collapse: separate;border-spacing: 1px;width:100%;font-size:12px;text-align:center;\" cellpadding=\"1px;\" cellspacing=\"1px;\">\r\n");
      out.write("\t\t<tr style=\"background-color:#f7f9fc;\">\r\n");
      out.write("\t\t\t<td style=\"width: 10%\">学号</td><td style=\"width: 10%\">姓名</td><td style=\"width: 10%\">性别</td>\r\n");
      out.write("\t\t\t<td style=\"width: 10%\">院系</td><td style=\"width: 10%\">学历</td><td style=\"width: 10%\">年级</td>\r\n");
      out.write("\t\t\t<td style=\"width: 10%\">联系方式</td><td style=\"width: 10%\">承担工作</td><td style=\"width: 10%\">操作</td>\r\n");
      out.write("\t\t</tr> \r\n");
      out.write("\t\t");

		List sexOptions = CEditConst.getsexOptions(userInfo);
		List IdentityOptions = CEditConst.getIdentityOptions(userInfo);
		List GradeNameOptions = CEditConst.getGradeNameOptions(userInfo);
		List DutyOPtions = util.getMemberDutyOptions();
		List tids = new ArrayList();
		if (TeamList.size()>0) {
			for(int i=0;i<TeamList.size();i++) {
				ClubMembers m = new ClubMembers();
				m = (ClubMembers)TeamList.get(i);
				tids.add((i+1)+"");
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr id=del");
      out.print(i+1 );
      out.write(" class=odd>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<input style=\"width: 100%\" id=\"Id_t");
      out.print(i+1);
      out.write("\" name=\"Id_t");
      out.print(i+1);
      out.write("\" value=\"");
      out.print(m.getId());
      out.write("\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t<input style=\"width: 100%\" id=\"Sno_t");
      out.print(i+1);
      out.write("\" name=\"Sno_t");
      out.print(i+1);
      out.write("\" value=\"");
      out.print(m.getMemberSno());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<input style=\"width: 100%\" id=\"SName_t");
      out.print(i+1);
      out.write("\" name=\"SName_t");
      out.print(i+1);
      out.write("\" value=\"");
      out.print(m.getMemberName());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<select id=\"Sex_t");
      out.print(i+1);
      out.write("\" name=\"Sex_t");
      out.print(i+1);
      out.write("\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t");
      out.print(HtmlTool.renderMulSelectOption(sexOptions,""+m.getMemberSex(),"Sex_t"+(i+1)) );
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<select id=\"Academy_t");
      out.print(i+1);
      out.write("\" name=\"Academy_t");
      out.print(i+1);
      out.write("\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t");
      out.print(HtmlTool.renderMulSelectOption(AcademyNameOptions,""+m.getMemberAcademy(),"Academy_t"+(i+1)) );
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<select id=\"Identity_t");
      out.print(m.getId());
      out.write("\" name=\"Identity_t");
      out.print(m.getId());
      out.write("\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t");
      out.print(HtmlTool.renderMulSelectOption(IdentityOptions,""+m.getIdentity(),"Identity_t"+(i+1)) );
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<select id=\"Grade_t");
      out.print(m.getId());
      out.write("\" name=\"Grade_t");
      out.print(m.getId());
      out.write("\"  style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t");
      out.print(HtmlTool.renderMulSelectOption(GradeNameOptions,""+m.getMemberGrade(),"Grade_t"+(i+1)) );
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<input style=\"width: 100%\" id=\"Phone_t");
      out.print(i+1);
      out.write("\" name=\"Phone_t");
      out.print((i+1));
      out.write("\" value=\"");
      out.print(m.getMemberPhone() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<select id=\"Duty_t");
      out.print(i+1);
      out.write("\" name=\"Duty_t");
      out.print(i+1);
      out.write("\"  style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t");
      out.print(HtmlTool.renderMulSelectOption(DutyOPtions,""+m.getMemberDuty(),"Duty_t"+(i+1)) );
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style='width:10%;'><img  style='cursor:point;' src='../main/images/delete.gif' onclick=javascript:deleteSponsor2('del");
      out.print(i+1 );
      out.write('\'');
      out.write(',');
      out.print(i+1 );
      out.write(") alt=删除  title=删除  border=0></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}
		}
		
      out.write("\r\n");
      out.write(" <input type=\"hidden\" id=\"Nums\" name=\"Nums\" value=\"");
      out.print(tids.size()>0?Tool.join(",",tids):"" );
      out.write("\"/>\r\n");
      out.write("\t</table>\r\n");
      out.write("    <table  id=\"SName\" style=\"border-collapse: separate;border-spacing: 1px;width:100%;font-size:12px;text-align:center;\" cellpadding=\"1px;\" cellspacing=\"1px;\">\r\n");
      out.write("\t<!-- <tr>\r\n");
      out.write("\t<td>学号</td><td>姓名</td><td>性别</td><td>院系</td><td>学历</td><td>年级</td><td>联系方式</td><td>承担工作</td><td><a href=\"#\" class='add_btn' onclick=\"addMember();\">本科生添加</a></td>\r\n");
      out.write("\t</tr> -->\r\n");
      out.write("\t");

	Map UserCnNameMap = CEditConst.getUserCnNameMap(userInfo);
	Map sexMap = CEditConst.getsexMap(userInfo);
	Map GradeNameMap = CEditConst.getGradeNameMap(userInfo);
	Map AcademyNameMap= CEditConst.getAcademyNameMap(userInfo);
	List sidsList = new ArrayList();
	if (club.getId()!=-1) {
		ClubMembers member = new ClubMembers();		
		List list = new ArrayList();
		list = util.getTeamList(club.getId(),"0");
		if (list.size()>0) {
			for (int i=0;i<list.size();i++) {
				//}
				member = (ClubMembers)list.get(i);
				sidsList.add(member.getMemberName()+"");
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr id=\"deleteSponsor_");
      out.print(member.getMemberName());
      out.write("\">\r\n");
      out.write("\t\t\t\t<input id=\"SName");
      out.print(member.getMemberName());
      out.write("\" name=\"SName");
      out.print(member.getMemberName());
      out.write("\" value=\"");
      out.print(member.getMemberName());
      out.write("\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">");
      out.print(member.getMemberSno());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">");
      out.print(UserCnNameMap.get(member.getMemberName())==null?"":UserCnNameMap.get(member.getMemberName()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">");
      out.print(sexMap.get(member.getMemberSex())==null?"":sexMap.get(member.getMemberSex()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">");
      out.print(AcademyNameMap.get(member.getMemberAcademy())==null?"":AcademyNameMap.get(member.getMemberAcademy()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\"><input type=\"hidden\" id=\"Identity");
      out.print(member.getMemberName());
      out.write("\" name=\"Identity");
      out.print(member.getMemberName());
      out.write("\" value=\"1\"/>本科</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">");
      out.print(GradeNameMap.get(member.getMemberGrade())==null?"":GradeNameMap.get(member.getMemberGrade()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\"><input style=\"width: 100%\" id=\"Phone");
      out.print(member.getMemberName());
      out.write("\" name=\"Phone");
      out.print(member.getMemberName());
      out.write("\" value=\"");
      out.print(member.getMemberPhone() );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<select id=\"Duty");
      out.print(member.getMemberName());
      out.write("\" name=\"Duty");
      out.print(member.getMemberName());
      out.write("\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t");
      out.print(HtmlTool.renderMulSelectOption(DutyOPtions,""+member.getMemberDuty(),"Duty"+member.getMemberName()) );
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t<img style=\"cursor:point;\" src='");
      out.print(HeadConst.apache_url);
      out.write("/main/images/delete.gif' onclick=\"javascript:deleteSponsor('deleteSponsor_");
      out.print(member.getMemberName() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(member.getMemberName() );
      out.write("')\" alt='删除' title='删除' border=0 />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}
		}
	}
	
      out.write("\r\n");
      out.write("\t<input id=\"SId\" name=\"SId\" value=\"");
      out.print(Tool.join(",",sidsList));
      out.write("\" type=\"hidden\"/>\r\n");
      out.write("\t</table>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"35\"><td colspan=\"4\" class=\"blocktitle\">成立社团的可行性、必要性论证</td></tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t     <td  colspan=\"4\" align=\"center\"><textarea name=\"Feasibility\"  maxlength=\"1000\" cols=\"150\" rows=\"10\">");
      out.print(club.getFeasibility() );
      out.write("</textarea></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("<tr height=\"35\"><td colspan=\"4\" class=\"blocktitle\">附件上传</td></tr>\r\n");
      out.write("<input type=\"hidden\" name=\"AddFileList\" id=\"AddFileList\" value=\"");
      out.print(club.getAddFileList());
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"Id\" id=\"Id\"value=\"");
      out.print(club.getId());
      out.write("\"/>\r\n");
      out.write("<tr id=\"postFormBookedBooths\">\r\n");
      out.write("\t<td class=\"form_label\"  width=\"14%\" >\r\n");
      out.write("\t<div align=\"right\">相关附件：</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"#FFFFFF\" colspan=\"3\" align=\"left\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" id=\"ShowFiles\">\r\n");
      out.write("\t\t\t");

				if(club.getId()!=-1){
					ClientAttach ca = new ClientAttach();
					//ca.setDataBase("sdtw");
					String ids = club.getAddFileList();
					if(ids!=null&&ids.trim().length()>0){
						String[] idArray = Tool.split(",",ids);
						for(int i=0;i<idArray.length;i++){
							ClientAttach ca1 = ca.getById(Tool.StrToInt(idArray[i]));
							if(ca1!=null){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr id=\"");
      out.print(ca1.getId() );
      out.write("\"><td><a href=\"");
      out.print(HeadConst.apache_url );
      out.write("/servlet/attach?type=otherattach&id=");
      out.print(ca1.getId() );
      out.write("\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src='");
      out.print(HeadConst.apache_url);
      out.write("/main/images/file1.gif' border=\"0\"/> ");
      out.print(ca1.getUploadName() );
      out.write("</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src='");
      out.print(HeadConst.apache_url);
      out.write("/main/images/delete.gif' alt='删除' title='删除' border=\"0\" onclick=\"javascript:deleteUpdateFile('");
      out.print(ca1.getUploadName());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ca1.getId() );
      out.write("')\" style=\"cursor:point;\"/></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
	}
								}
							}
						}
					
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");
if(club.getId()==-1||"update".equals(cmd)){
      out.write("\r\n");
      out.write("\t\t<input type=\"file\" name=\"OtherAttach\" id=\"OtherAttach\" size=\"40\"/> \r\n");
      out.write("\t\t<input type=\"button\" value=\"上传\" id=\"btn_up\"  onclick=\"checkFileType();\" class=\"formbtn\" style=\"color:black;background-color: #e3e5e8;\"/>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t<img style=\"display:none\" id=\"load1\" src=\"");
      out.print(HeadConst.apache_url);
      out.write("/main/images/loading.gif\"/>\r\n");
      out.write("\t    <div style=\"color:red\">请上传doc、docx、xlsx或xls格式文件，文件最大5M</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<!-- <tr>\r\n");
      out.write("\t<td align=\"right\" >&nbsp;指导老师情况：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\">&nbsp;</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td  align=\"right\">&nbsp;拟任会长：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\">&nbsp;</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td  align=\"right\">&nbsp;拟任团支书：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\">&nbsp;</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td  align=\"right\">&nbsp;拟任财务负责人：</td>\r\n");
      out.write("    <td align=\"left\" colspan=\"3\">&nbsp;</td>\r\n");
      out.write("</tr> -->\r\n");
      out.write("\r\n");
      out.write("\t<tr height=\"35\"><td colspan=\"4\" class=\"blocktitle\">审查意见</td></tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t     <td  align=\"right\">&nbsp;<font color=\"red\">*&nbsp;</font>指导教师意见：</td>\r\n");
      out.write("\t     <td  colspan=\"3\" align=\"left\"><textarea name=\"CommentTea\"  maxlength=\"200\" cols=\"130\" rows=\"4\">");
      out.print(club.getCommentTea() );
      out.write("</textarea></td>\r\n");
      out.write("\t</tr> \r\n");
      out.write("\t");

if(SdtwConst.CHECKFLAG_XYTG.equals(club.getCheckFlag())||SdtwConst.CHECKFLAG_XYWTG.equals(club.getCheckFlag())||SdtwConst.CHECKFLAG_XXTG.equals(club.getCheckFlag())||SdtwConst.CHECKFLAG_XXWTG.equals(club.getCheckFlag())){
      out.write(" \r\n");
      out.write("<tr height=\"35\"><td colspan=\"4\" class=\"blocktitle\">学院审核意见</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t     <td  align=\"right\">&nbsp;学院意见：</td>\r\n");
      out.write("\t     <td  colspan=\"3\" align=\"left\">");
      out.print(club.getCommentAcademy() );
      out.write("</td>\r\n");
      out.write("</tr> \r\n");
} 
      out.write('\r');
      out.write('\n');

if(SdtwConst.CHECKFLAG_XXTG.equals(club.getCheckFlag())||SdtwConst.CHECKFLAG_XXWTG.equals(club.getCheckFlag())){

      out.write("\r\n");
      out.write("<tr height=\"35\"><td colspan=\"4\" class=\"blocktitle\">团委审核意见</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t     <td  align=\"right\">&nbsp;团委意见：</td>\r\n");
      out.write("\t     <td  colspan=\"3\" align=\"left\">");
      out.print(club.getCommenttw() );
      out.write("</td>\r\n");
      out.write("</tr> \r\n");
}

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <th  colspan=\"4\" align=\"center\">\r\n");
      out.write("    ");

    if("view".equals(cmd)||"viewlist".equals(cmd)){
      out.write("\r\n");
      out.write("    \t<a href=\"#\" onclick=\"formcancel('");
      out.print(backurl+"?active="+active);
      out.write("')\" >返回</a>\r\n");
      out.write("    ");
}else{
      out.write("\r\n");
      out.write("        <input type=\"button\" class=\"button\" value=\"确定\" name=\"btn1\" onclick=\"formsubmit()\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        <input type=\"button\" class=\"button\" value=\"取消\" name=\"btn2\" onclick=\" formcancel('");
      out.print(backurl+"?active="+active);
      out.write("')\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    ");
}
    
      out.write("\r\n");
      out.write("    </th>\r\n");
      out.write("</tr> \r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- <script src=\"../js/jquery.editable-1.0.1.js\"></script> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
