/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-26 07:40:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main.campus;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xietong.software.base.Power;
import com.xietong.software.sdtw.club.ClubUtil;
import com.xietong.software.sdtw.*;
import com.xietong.software.sdtw.db.*;
import com.xietong.software.util.*;
import com.xietong.software.common.*;
import org.apache.commons.logging.*;
import java.io.*;
import java.util.*;
import com.xietong.software.common.UserInfo;
import com.xietong.software.common.HeadConst;
import com.xietong.software.util.Tool;

public final class CampusActivityForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/main/js/jsheader.jsp", Long.valueOf(1485156249000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var GBasePath = \"");
      out.print(HeadConst.root_url_path);
      out.write("\";\r\n");
      out.write("var GResPath = \"");
      out.print(HeadConst.apache_url);
      out.write("/main\";\r\n");
{
      out.write("var GImagePath = \"");
      out.print(HeadConst.apache_url);
      out.write("/main/images/skin/");
UserInfo ui = Tool.getUserInfo(request); if (ui == null) out.print("blue"); else out.print(ui.getSkinId());
      out.write('"');
      out.write(';');
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');

	Log log = LogFactory.getLog(CampusActivity.class);
	String msg = (String)request.getAttribute("msg");
	if ((msg != null)) {
    		out.print(HtmlTool.msgBox(request, msg));
    		return;
	}
	String cmd = ParamUtils.getParameter(request, "cmd", "insert");
	int currpage = ParamUtils.getIntParameter(request, "page", 1);
	CampusActivity v = (CampusActivity)request.getAttribute("fromBean");
	if (v == null) {
    		out.print(HtmlTool.msgBox(request, "请先调用Action.jsp！"));
    		return;
	}
	log.debug(request.getAttribute("classname") + "Form");
	String[] dickeys = (String[])request.getAttribute("dickeys");
	String[][] dicvalues = (String[][])request.getAttribute("dicvalues");
	List diclist = new ArrayList();
	for (int i = 0; i < dickeys.length; i ++) {
    		diclist.add("\"" + dickeys[i] + "\": [\"" + Tool.join("\", \"", dicvalues[i]) + "\"]");
	}
	Map extMaps = (Map)request.getAttribute("Ext");
	List paras = HttpTool.getSavedUrlForm(request, "Ext");
	List urls = (List)paras.get(0);
	List forms = (List)paras.get(1);
	urls.addAll((List)paras.get(2));
	forms.addAll((List)paras.get(3));
	String url = Tool.join("&", urls);
	//默认值定义
	UserInfo userInfo = Tool.getUserInfo(request);
	if(userInfo == null){
    		out.print(HtmlTool.msgBox(request, "请先登录"));
    		return;
	}
	List AcademyNameoptions = CEditConst.getAcademyNameOptions(userInfo,"");
List cdt = new ArrayList();
if(!"".equals(v.getAcademy().trim())){
cdt.add("id not in("+v.getAcademy()+")");
}
cdt.add("flag=1");	
List AcademyNameoptions2 = COptionConst.getAcademyNameOptions(userInfo,cdt);

cdt.clear();
if(!"".equals(v.getAcademy().trim())) {
	cdt.add("id  in("+v.getAcademy()+")");
	cdt.add("flag=1");
} else {
	cdt.add("1=-1");
}
List AcademyNameoptions3 = COptionConst.getAcademyNameOptions(userInfo,cdt);

List OrgNameoptions = CEditConst.getOrgCityNameOptions(userInfo);
List ActivitykindTypeoptions = CEditConst.getActivitykindTypeOptions(userInfo,"-1");
List TotalRoundsoptions = (List)request.getAttribute("TotalRoundsoptions");
List ActivityLeveloptions = (List)request.getAttribute("ActivityLeveloptions");
int ActivitykindType = ParamUtils.getIntParameter(request,"_ActivitykindType_",-1);
ClubUtil util = new ClubUtil();
cdt.clear();
//指导单位
if(userInfo.hasFunPower(Power.UserAdminPower)){
	cdt.add("deptid="+userInfo.getDeptId());
}
/* cdt.add("(roles=3)");
List UserCnNameOptions = util.getUserCnNameOptions(cdt); */

Map userMap = CEditConst.getUserCnNameMap(userInfo);
String name = (String)userMap.get(v.getActivityPrincipal()+"")==null?v.getActivityPrincipal():(String)userMap.get(v.getActivityPrincipal()+"");
int _ActivitykindType_ = ParamUtils.getIntParameter(request,"_ActivitykindType_",-1);

      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>");
      out.print(request.getAttribute("describe"));
      out.write("</title>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/main/jqueryui.jsp", out, true);
      out.write("\r\n");
      out.write("\t\t<!-- 左右列表 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/bootstrap-3.3.7/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"js/bootstrap-3.3.7/dist/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<!-- <link rel=\"stylesheet\" href=\"css/prettify.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style.css\" /> -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/multiselect.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/multiselect.min.js\"></script>\r\n");
      out.write("\t\t<!-- 左右列表 -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(HeadConst.apache_url);
      out.write("/main/images/skin/");
      out.print(userInfo.getSkinId());
      out.write("/css.css\">\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"");
      out.print(HeadConst.apache_url);
      out.write("/main/js/validation-framework.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tValidationFramework.init(\"");
      out.print(request.getAttribute("classname"));
      out.write("_validation.xml\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(userInfo.getRootUrl());
      out.write("/main/js/formfunction.js\"></script>\r\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"");
      out.print(HeadConst.apache_url);
      out.write("/main/js/datepicker/WdatePicker.js\"></script>\r\n");
      out.write("\t\t<script src=\"../../js/jquery.editable-1.0.1.js\"></script>\r\n");
      out.write("\t\t<link type=\"text/css\" href=\"");
      out.print(HeadConst.apache_url+"/main/" );
      out.write("js/jquery-ui-1.10.2/themes/base/jquery-ui-1.8.4.custom.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t//#form td {padding: 0px;}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar url_para = \"");
      out.print(url);
      out.write("\";\r\n");
      out.write("\t\t\tvar dic = {");
      out.print(Tool.join(", ", diclist));
      out.write("};\r\n");
      out.write("\t\t\tvar keyfield = \"");
      out.print((String)request.getAttribute("keyfield"));
      out.write("\";\r\n");
      out.write("\t\t\tvar allfields = [\"");
      out.print(Tool.join("\", \"", (String[])request.getAttribute("allfields")));
      out.write("\"];\r\n");
      out.write("\t\t\tvar fields = [\"");
      out.print(Tool.join("\", \"", (String[])request.getAttribute("fields")));
      out.write("\"];\r\n");
      out.write("\t\t\tvar options= {");
      out.print(HtmlTool.getJsOptions(request));
      out.write("};\r\n");
      out.write("\t\t\tfunction init() {\r\n");
      out.write("    \t\t\t\tprepareForm(\"");
      out.print(request.getAttribute("classname"));
      out.write("\", dic, \"");
      out.print(userInfo.getPower());
      out.write("\");\r\n");
      out.write("    \t\t\t\t$('#multiselect').multiselect();\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t$(\"#UserName\").click(function(){\r\n");
      out.write("    \t\t\t\t\t $('#ActivityPrincipal').val(\"\");\r\n");
      out.write("    \t\t\t\t})\r\n");
      out.write("    \t\t\t\t$(\"#UserName\").autocomplete({\r\n");
      out.write("    \t\t\t\t\tsource: \"../base/UserCodeAction.jsp?cmd=getUsers\",\r\n");
      out.write("    \t\t\t\t\t select: function( event, ui ) {\r\n");
      out.write("    \t\t\t\t          $('#UserName').val(ui.item.label);\r\n");
      out.write("    \t\t\t\t          $('#ActivityPrincipal').val(ui.item.value);\r\n");
      out.write("    \t\t\t\t          return false;\r\n");
      out.write("    \t\t\t\t        }\r\n");
      out.write("    \t\t\t\t});\t\r\n");
      out.write("    \t\t\t\tvar rowspan = document.getElementById(\"teamtable\").rows.length;\r\n");
      out.write("    \t\t\t\t$('#Nums').val(rowspan-1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction Jump(f){\r\n");
      out.write("\t\t\t\t$('#commentFrame'+f).attr(\"src\",\"CampusParticipateAction.jsp?_flag_=\"+f+\"&_CampusActivityId_=");
      out.print(v.getId());
      out.write("\") \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction checkForm(){\r\n");
      out.write("\t\t\t\t$('#UserName').removeAttr(\"style\");\r\n");
      out.write("\t\t\t\tif($('#ActivityPrincipal').val() == '' && $('#UserName').val() == \"\"){\r\n");
      out.write("\t\t\t\t\t$(\"#errorDiv\").html(\"请填写用户！\");\r\n");
      out.write("\t\t\t\t\t$('#UserName').css(\"border\",\" 2px solid rgb(255, 204, 136)\");\r\n");
      out.write("\t\t\t\t\t$('#UserName').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if($('#ActivityPrincipal').val() == '' &&  $('#UserName').val() != \"\"){\r\n");
      out.write("\t\t\t\t\t$(\"#errorDiv\").html(\"请选择正确的用户信息！\");\r\n");
      out.write("\t\t\t\t\t$('#UserName').css(\"border\",\" 2px solid rgb(255, 204, 136)\");\r\n");
      out.write("\t\t\t\t\t$('#UserName').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction val(){\r\n");
      out.write("\t\t\t\tvar val = \"\";     \r\n");
      out.write("\t\t\t     $(\"#multiselect_to option\").each(function(){  //遍历所有option  \r\n");
      out.write("\t\t\t          var txt = $(this).val();   //获取option值   \r\n");
      out.write("\t\t\t          if(txt!=''){  \r\n");
      out.write("\t\t\t               val+=txt+\",\";\r\n");
      out.write("\t\t\t          }  \r\n");
      out.write("\t\t\t     })  \r\n");
      out.write("\t\t\t     if(val.length>0){\r\n");
      out.write("\t\t\t    \t val = val.substring(0,val.length-1);\r\n");
      out.write("\t\t\t     }\r\n");
      out.write("\t\t\t     $('#Academy').val(val);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction join(flag) {\r\n");
      out.write("\t\t\t\tif(flag==0){\r\n");
      out.write("\t\t\t\t\t$('#Academy').val(\"\");\r\n");
      out.write("\t\t\t\t\t$('#xy').hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(flag==1){\r\n");
      out.write("\t\t\t\t\t$('#xy').show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\tvar xyOrAll = $('input[name=\"ApplicationRange\"]').filter(':checked').val();\r\n");
      out.write("\t\t\t\t join(xyOrAll);\r\n");
      out.write("\t\t\t\t $('input[name=\"ApplicationRange\"]').click(function(){\r\n");
      out.write("\t\t\t\t\t var xyOrAll = $(this).filter(':checked').val();\r\n");
      out.write("\t\t\t\t\t join(xyOrAll);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction submitthis(){\r\n");
      out.write("\t\t\t\tvar ApplicationRange = $('input:radio[name=\"ApplicationRange\"]:checked').val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar id_array=new Array();\r\n");
      out.write("\t\t\t\t$('input[name=\"Campus\"]:checked').each(function(){  \r\n");
      out.write("\t\t\t\t    id_array.push($(this).val());//向数组中添加元素  \r\n");
      out.write("\t\t\t\t});  \r\n");
      out.write("\t\t\t\tval();\r\n");
      out.write("\t\t\t\tvar Academy = $('#Academy').val();\r\n");
      out.write("\t\t\t\tif(ApplicationRange==\"\"||ApplicationRange==\"-1\"){\r\n");
      out.write("\t\t\t\t\t$('#errorDiv').html(\"请选择申请范围\");\r\n");
      out.write("\t\t\t\t\t$('#ApplicationRange').focus();\r\n");
      out.write("\t\t\t\t\treturn ;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(id_array.length==0){\r\n");
      out.write("\t\t\t\t\t$('#errorDiv').html(\"请选择参与城市\");\r\n");
      out.write("\t\t\t\t\t$('input:checkbox[name=\"Campus\"]').focus();\r\n");
      out.write("\t\t\t\t\treturn ;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(ApplicationRange===\"1\"){\r\n");
      out.write("\t\t\t\t\tvar Academy = $('#Academy').val();\r\n");
      out.write("\t\t\t\t\tif(Academy==\"\"||Academy==\"-1\"){\r\n");
      out.write("\t\t\t\t\t\t$('#errorDiv').html(\"请选择学院\");\r\n");
      out.write("\t\t\t\t\t\t$('#multiselect').focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar l = $('#teamtable input').length;\r\n");
      out.write("\t\t\t\tif (l==0) {\r\n");
      out.write("\t\t\t\t\talert(\"请设置荣誉！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(!chekSname('teamtable')){\r\n");
      out.write("\t\t\t\t\talert(\"请将荣誉信息填写完整！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#postForm').submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction chekSname(id) {\r\n");
      out.write("\t\t\t\tvar f = true;\r\n");
      out.write("\t\t\t\t$(\"#\"+id).find(\"input\").each(function () {\r\n");
      out.write("\t\t\t        if ($(this).val() == \"\") {\r\n");
      out.write("\t\t\t        \t//alert($(this).attr(\"id\"))\r\n");
      out.write("\t\t\t            $(this).focus();\r\n");
      out.write("\t\t\t            f=false;\r\n");
      out.write("\t\t\t        }else{\r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    })\r\n");
      out.write("\t\t\t    return f;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t    function checkPersonNumber(flag){\r\n");
      out.write("\t\t    \tif(flag==1){\r\n");
      out.write("\t\t    \t\tvar PersonNumber1 = $('#PersonNumber1').val();\r\n");
      out.write("\t\t    \t\tif(PersonNumber1>0){\r\n");
      out.write("\t\t    \t\t\t$('#PersonNumber2' ).attr(\"checked\",false);\r\n");
      out.write("\t\t    \t\t\t$('#PersonNumber').val(PersonNumber1);\r\n");
      out.write("\t\t    \t\t}\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \tif(flag==2){\r\n");
      out.write("\t\t    \t\t $('#PersonNumber1').val(\"\");\r\n");
      out.write("\t\t    \t\t $('#PersonNumber').val(\"-1\");\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    function addItem(){\r\n");
      out.write("\t\t    \tvar rowspan = document.getElementById(\"teamtable\").rows.length;\r\n");
      out.write("\t\t    \tvar bg = \"bgcolor='#ffffff'\";\r\n");
      out.write("\t\t    \tif(rowspan%2==0){\r\n");
      out.write("\t\t    \t\tbg = \"bgcolor='#f7f9fc'\";\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \tvar HonorName = $('#HonorName'+(rowspan-1)).val();\r\n");
      out.write("\t\t    \tvar Num = $('#Num'+(rowspan-1)).val();\r\n");
      out.write("\t\t    \tif(HonorName==\"\"){\r\n");
      out.write("\t\t    \t\t$('#HonorName'+(rowspan-1)).focus();\r\n");
      out.write("\t\t    \t\talert(\"请填写完整！\");\r\n");
      out.write("\t\t    \t\treturn;\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \tif(Num==\"\"){\r\n");
      out.write("\t\t    \t\t$('#Num'+(rowspan-1)).focus();\r\n");
      out.write("\t\t    \t\talert(\"请填写完整！\");\r\n");
      out.write("\t\t    \t\treturn;\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \t$('#Nums').val(rowspan);\r\n");
      out.write("\t\t    \t$(\"#teamtable\").append(\r\n");
      out.write("\t\t    \t\"<tr \"+bg+\" onMouseOver=\\\"addClass(this,'data_bgcolor_over');\\\"  onMouseOut=\\\"removeClass(this,'data_bgcolor_over');\\\">\"+\r\n");
      out.write("\t\t    \t\t\"<td> <input  type='text' id='HonorName\"+rowspan+\"' size='15' name='HonorName\"+rowspan+\"' /></td>\"+\r\n");
      out.write("\t\t    \t\t\"<td><input  type='text' id='Num\"+rowspan+\"'size='15' name='Num\"+rowspan+\"' /></td>\"+\r\n");
      out.write("\t\t    \t\t\"<td></td>\"+\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t\"</tr>\"\r\n");
      out.write("\t\t    \t);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    function addClass(element, className) { \r\n");
      out.write("\t\t\t\tif (!this.hasClass(element, className)) \r\n");
      out.write("\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\telement.className += \" \"+className; \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction hasClass(element, className) { \r\n");
      out.write("\t\t\t\tvar reg = new RegExp('(\\\\s|^)'+className+'(\\\\s|$)'); \r\n");
      out.write("\t\t\t\treturn element.className.match(reg); \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\tfunction removeClass(element, className) { \r\n");
      out.write("\t\t\t\tif (hasClass(element, className)) { \r\n");
      out.write("\t\t\t\t\tvar reg = new RegExp('(\\\\s|^)'+className+'(\\\\s|$)'); \r\n");
      out.write("\t\t\t\t\telement.className = element.className.replace(reg,' '); \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body onload=\"init();\">\r\n");
      out.write("\t\t<div class=\"browsetitle\">\r\n");
      out.write("\t\t\t<div class=\"browsetitleleft\">\r\n");
      out.write("\t\t\t");

			String describe = ParamUtils.getAttribute(request,"describe",""); 
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"browsetitle001\">");
      out.print(describe );
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div class=\"browsetitle002\">");
      out.print(XtUtil.getSpell(describe) );
      out.write("</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"browsetitleright\">\r\n");
      out.write("\t\t\t\t<div class=\"anniulist2\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"CampusActivityAction.jsp?cmd=list&page=");
      out.print(currpage);
      out.print(((url.length() == 0) ? "" : "&" + url));
      out.write("\" >返回</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						if ((userInfo.getId()+"").equals(v.getAddperson())||"save".equals(cmd)) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" onclick=\"javascript:if(checkForm()&&doValidate('postForm')) submitthis();\">保存</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"errorDiv\" style=\"color:red;font-weight:bold\"></div>\r\n");
      out.write("\t\t<div class=\"browsetable\" id=\"form\">\r\n");
      out.write("\t\t<div id=\"tabs\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#tabs-1\">基本信息</a></li>\r\n");
      out.write("\t\t\t\t<li onclick=\"Jump(1)\"><a href=\"#tabs-2\">报名管理</a></li>\r\n");
      out.write("\t\t\t\t<li onclick=\"Jump(2)\"><a href=\"#tabs-3\">成绩管理</a></li>\r\n");
      out.write("\t\t\t\t<li onclick=\"Jump(3)\"><a href=\"#tabs-4\">荣誉管理</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getAttribute("classname"));
      out.write("Action.jsp\" method=\"post\" name=\"postForm\" id=\"postForm\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"");
      out.print(cmd);
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"page\" value=\"");
      out.print(currpage);
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"Addtime\" id=\"Addtime\" size=\"0\" value=\"");
      out.print(Tool.stringOfDateTime(v.getAddtime()));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"Addperson\" id=\"Addperson\" size=\"45\" maxsize=\"45\" value=\"");
      out.print(v.getAddperson());
      out.write("\">\r\n");
      out.write("               \t<input type=\"hidden\" name=\"ModifyTime\" id=\"ModifyTime\" size=\"0\" value=\"");
      out.print(Tool.stringOfDateTime(v.getModifyTime()));
      out.write("\">\r\n");
      out.write("               \t<input type=\"hidden\" name=\"ModifyPerson\" id=\"ModifyPerson\" size=\"45\" maxsize=\"45\" value=\"");
      out.print(v.getModifyPerson());
      out.write("\">\r\n");
      out.write("               \t<input type=\"hidden\" name=\"Honor\" id=\"Honor\" value=\"");
      out.print(v.getHonor());
      out.write("\"/>\t\r\n");
      out.write("               \t<input type=\"hidden\" id=\"Academy\" name=\"Academy\" value=\"");
      out.print(v.getAcademy());
      out.write("\"/>\t\t\r\n");
      out.write("               \t<input type=\"hidden\" id=\"PersonNumber\" name=\"PersonNumber\" value=\"");
      out.print(v.getPersonNumber());
      out.write("\"/>\t\r\n");
      out.write("               \t<input type=\"hidden\" id=\"Nums\" name=\"Nums\"/><!-- 荣誉条数 -->\t\t\t\r\n");
      out.write("               \t<input type=\"hidden\" id=\"_ActivitykindType_\" name=\"_ActivitykindType_\" value=\"");
      out.print(_ActivitykindType_);
      out.write("\"/>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<div id=\"tabs-1\" style=\"border: 0px;padding: 0px;\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<table style=\"background-color: #e3e5e8;border-spacing: 1px;border-collapse: separate;\" width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"4\" cellspacing=\"1\">\r\n");
      out.write("<input type=\"hidden\" name=\"Id\" value=\"");
      out.print(v.getId());
      out.write("\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">活动名称</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"ActivityName\" name=\"ActivityName\" value=\"");
      out.print(v.getActivityName());
      out.write("\"/>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">活动类别</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.print(HtmlTool.renderSelect(ActivitykindTypeoptions, v.getActivitykindType(), "ActivitykindType", ""+ActivitykindType,true));
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">活动组织单位</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t");

														    			if(userInfo.hasFunPower(Power.UserAdminPower)){
														    			
      out.write('\r');
      out.write('\n');
      out.print(HtmlTool.renderSelect(AcademyNameoptions, v.getOrgacadeMy().equals("")?userInfo.getDeptId()+"":v.getOrgacadeMy(), "OrgacadeMy", "",true));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																		if(userInfo.hasFunPower(Power.ADMINPOWER)||userInfo.hasFunPower(Power.WHHD)){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t山东大学团委<input type=\"hidden\" id=\"OrgacadeMy\" name=\"OrgacadeMy\" value=\"-1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
}
																		
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">活动级别</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.print(HtmlTool.renderSelect(ActivityLeveloptions, v.getActivityLevel(), "ActivityLevel", ""));
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">负责人</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t                        <input name=\"UserName\" id=\"UserName\" value=\"");
      out.print((name == null ?"":name));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"ActivityPrincipal\" id=\"ActivityPrincipal\" value=\"");
      out.print(v.getActivityPrincipal());
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br/><font color='red'>录入姓氏或学号，请在下拉中选择</font>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">联系方式</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"Contact\" id=\"Contact\" value=\"");
      out.print(v.getContact());
      out.write("\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">活动轮次</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.print(HtmlTool.renderSelect(TotalRoundsoptions, v.getTotalRounds(), "TotalRounds", ""));
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">报名截止日期</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"Deadline\"  id=\"Deadline\" size=\"0\" value=\"");
      out.print(Tool.stringOfDate(Tool.stringToDate(v.getDeadline())));
      out.write("\" readonly onclick=\"WdatePicker({dateFmt:'yyyy-MM-dd',onpicked:function(){}})\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\" >所需人数</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"PersonNumber1\" id=\"PersonNumber1\"  value=\"");
      out.print(Tool.StrToInt(v.getPersonNumber())>0?v.getPersonNumber():"");
      out.write("\" onblur=\"checkPersonNumber(1)\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"PersonNumber2\" name=\"PersonNumber2\" value=\"-1\" type=\"checkbox\" onblur=\"checkPersonNumber(2)\" ");
      out.print(v.getPersonNumber().equals("-1")?"checked=\"checked\"":"" );
      out.write(" />不限\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">第一轮日期</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input onclick=\"WdatePicker({el:'ActivityDate1',dateFmt:'yyyy-MM-dd'})\" name=\"ActivityDate1\" readonly id=\"ActivityDate1\" size=\"0\" value=\"");
      out.print(v.getActivityDate1());
      out.write("\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">第一轮地点</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"3\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"ActivityPlace1\" name=\"ActivityPlace1\" size=\"50\" value=\"");
      out.print(v.getActivityPlace1());
      out.write("\" />\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">第二轮日期</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"ActivityDate2\"  id=\"ActivityDate2\"  value=\"");
      out.print(v.getActivityDate2());
      out.write("\" readonly onclick=\"WdatePicker({dateFmt:'yyyy-MM-dd',minDate:'#F{$dp.$D(\\'ActivityDate1\\')}',onpicked:function(){}})\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">第二轮地点</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"3\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"ActivityPlace2\" name=\"ActivityPlace2\" size=\"50\" value=\"");
      out.print(v.getActivityPlace2());
      out.write("\" />\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">第三轮日期</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"ActivityDate3\"  id=\"ActivityDate3\"  value=\"");
      out.print(v.getActivityDate3());
      out.write("\" readonly onclick=\"WdatePicker({dateFmt:'yyyy-MM-dd',minDate:'#F{$dp.$D(\\'ActivityDate2\\')}',onpicked:function(){}})\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">第三轮地点</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"3\" >\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"ActivityPlace3\" name=\"ActivityPlace3\" size=\"50\" value=\"");
      out.print(v.getActivityPlace3());
      out.write("\" />\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\"><font color=\"red\">*</font>荣誉设置：</td>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"5\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t    \t<table id=\"teamtable\"   style=\"border-collapse: separate;border-spacing: 1px;width:100%;font-size:12px;text-align:center;\" cellpadding=\"1px;\" cellspacing=\"1px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr style=\"background-color:#f7f9fc;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td >荣誉类型</td><td>人数</td><td><a href=\"#\" onclick=\"addItem();return false;\" style=\"color: red;\">添加</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																		cdt = new ArrayList();
																		if (v.getId()!=-1) {
																		cdt.add("ActivityId = "+v.getId());
																		Honor h  = new Honor();
																		List list = new ArrayList();
																		list = h.query(cdt);
																		if(list.size()>0){
																			for(int i=0;i<list.size();i++){
																				h = (Honor)list.get(i);
																				String bgcolor="bgcolor=#ffffff";
																				if(i%2==0){
																					bgcolor="bgcolor=#f7f9fc";
																				}
																				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"honorId");
      out.print(i+1 );
      out.write("\" name=\"honorId");
      out.print(i+1 );
      out.write("\" value=\"");
      out.print(h.getId());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr ");
      out.print(bgcolor );
      out.write(" onMouseOver=\"addClass(this,'data_bgcolor_over');\"  onMouseOut=\"removeClass(this,'data_bgcolor_over');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td > <input  type=\"text\" name=\"HonorName");
      out.print(i+1 );
      out.write("\" size=\"15\" id=\"HonorName");
      out.print(i+1);
      out.write("\" value=\"");
      out.print(h.getHonorName());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td ><input type=\"text\" name=\"Num");
      out.print(i+1 );
      out.write("\" size=\"15\" id=\"Num");
      out.print(i+1 );
      out.write("\" value=\"");
      out.print(h.getIsEnable()==0?1:h.getIsEnable());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
}
																		}
																		}
																		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t</td>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">详细介绍</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"5\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea style=\"width: 90%;\" name=\"ActivityExplain\" id=\"ActivityExplain\" cols=\"40\" rows=\"2\">");
      out.print(v.getActivityExplain());
      out.write("</textarea>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">参与城市</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"5\">\r\n");
      out.print(HtmlTool.renderCheckBox(OrgNameoptions, v.getCampus(), "Campus", ""));
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">申请范围</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"5\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t");

                    														List ApplicationRangeOptions = util.getApplicationRangeOptions();
                    														
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(HtmlTool.renderRadio(ApplicationRangeOptions, v.getApplicationRange(), "ApplicationRange","0"));
      out.write("\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t<tr id=\"xy\" style=\"display: none;\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" class=\"form_label\">学院</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t<td align=\"left\"  bgcolor=\"#ffffff\" colspan=\"5\">\r\n");
      out.write("\t\t    <div class=\"row\" style=\"width: 100%;\">\r\n");
      out.write("    \t<div class=\"col-xs-5\">\r\n");
      out.write("    \t\t<select name=\"from\" id=\"multiselect\" class=\"form-control\" size=\"15\" multiple=\"multiple\">\r\n");
      out.write("    \t\t\t");
      out.print(HtmlTool.renderSelectOption(AcademyNameoptions2, v.getAcademy(), ""));
      out.write("\r\n");
      out.write("    \t\t</select>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<div class=\"col-xs-2\">\r\n");
      out.write("    \t\t<button type=\"button\" id=\"multiselect_rightAll\" class=\"btn btn-block\"><i class=\"glyphicon glyphicon-forward\"></i></button>\r\n");
      out.write("    \t\t<button type=\"button\" id=\"multiselect_rightSelected\" class=\"btn btn-block\"><i class=\"glyphicon glyphicon-chevron-right\"></i></button>\r\n");
      out.write("    \t\t<button type=\"button\" id=\"multiselect_leftSelected\" class=\"btn btn-block\"><i class=\"glyphicon glyphicon-chevron-left\"></i></button>\r\n");
      out.write("    \t\t<button type=\"button\" id=\"multiselect_leftAll\" class=\"btn btn-block\"><i class=\"glyphicon glyphicon-backward\"></i></button>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<div class=\"col-xs-5\">\r\n");
      out.write("    \t\t<select name=\"to\" id=\"multiselect_to\" class=\"form-control\" size=\"15\" multiple=\"multiple\">\r\n");
      out.write("    \t\t");
      out.print(HtmlTool.renderSelectOption(AcademyNameoptions3, v.getAcademy(), ""));
      out.write("\r\n");
      out.write("    \t\t</select>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<div id=\"tabs-2\" style=\"border: 0px; padding: 0px;\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<iframe  class=\"commentFrame1\" name=\"commentFrame1\" id=\"commentFrame1\"  frameborder='0' marginheight=\"0\" marginwidth=\"0\" width=\"100%\" scrolling=\"auto\" height=\"500px\"></iframe>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<div id=\"tabs-3\" style=\"border: 0px; padding: 0px;\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<iframe  class=\"commentFrame2\" name=\"commentFrame2\" id=\"commentFrame2\"  frameborder='0' marginheight=\"0\" marginwidth=\"0\" width=\"100%\" scrolling=\"auto\" height=\"500px\"></iframe>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<div id=\"tabs-4\" style=\"border: 0px; padding: 0px;\">\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t<iframe  class=\"commentFrame3\" name=\"commentFrame3\" id=\"commentFrame3\"  frameborder='0' marginheight=\"0\" marginwidth=\"0\" width=\"100%\" scrolling=\"auto\" height=\"500px\"></iframe>\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$( \"#tabs\" ).tabs();\r\n");
      out.write("\t\t$(\"#tabs\").tabs('option','active', 0); \r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
