//自动生成的程序，请不要修改，下次生成的时候会覆盖
package com.xietong.software.common;
import java.util.*;
import com.xietong.software.common.*;
import com.xietong.software.util.*;
import com.xietong.software.sdtw.db.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
public class CInitData {
    //database sdtw
    public static void initSdtw(String dbname) {
        (new com.xietong.software.sdtw.db.Academy(dbname)).init();
        (new com.xietong.software.sdtw.db.StandardupGrade(dbname)).init();
        (new com.xietong.software.sdtw.db.StandardupGrade_File(dbname)).init();
        (new com.xietong.software.sdtw.db.UserAccounts(dbname)).init();
        (new com.xietong.software.sdtw.db.AddBookGroups(dbname)).init();
        (new com.xietong.software.sdtw.db.AddBookPerson(dbname)).init();
        (new com.xietong.software.sdtw.db.Places(dbname)).init();
        (new com.xietong.software.sdtw.db.Places_Applytable(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentUnion(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentUnionDept(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentUnionMember(dbname)).init();
        (new com.xietong.software.sdtw.db.Club(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubActivities(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubActivityParticipate(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubActivityProject(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubMembers(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubModify(dbname)).init();
        (new com.xietong.software.sdtw.db.Club_Regist(dbname)).init();
        (new com.xietong.software.sdtw.db.InnovationCompetition(dbname)).init();
        (new com.xietong.software.sdtw.db.InnovationCompetitionProject(dbname)).init();
        (new com.xietong.software.sdtw.db.InnovationCompetitionAwarditem(dbname)).init();
        (new com.xietong.software.sdtw.db.ChuangKu(dbname)).init();
        (new com.xietong.software.sdtw.db.ChuangkuDeclare(dbname)).init();
        (new com.xietong.software.sdtw.db.CampusActivity(dbname)).init();
        (new com.xietong.software.sdtw.db.CampusActivityKind(dbname)).init();
        (new com.xietong.software.sdtw.db.CampusParticipate(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubTeacher(dbname)).init();
        (new com.xietong.software.sdtw.db.TrainingArrangement(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerActivity(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerParticipate(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerProject(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerProjectParticipate(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerProjectTeammember(dbname)).init();
        (new com.xietong.software.sdtw.db.Practice(dbname)).init();
        (new com.xietong.software.sdtw.db.PracticeDeclare(dbname)).init();
        (new com.xietong.software.sdtw.db.PracticeDeclareTeammember(dbname)).init();
        (new com.xietong.software.sdtw.db.PracticeReport(dbname)).init();
        (new com.xietong.software.sdtw.db.Subject(dbname)).init();
        (new com.xietong.software.sdtw.db.SubjectFile(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentClassDuty(dbname)).init();
        (new com.xietong.software.sdtw.db.Survey_Basicinfo(dbname)).init();
        (new com.xietong.software.sdtw.db.SurveyAnswer(dbname)).init();
        (new com.xietong.software.sdtw.db.SurveyItems(dbname)).init();
        (new com.xietong.software.sdtw.db.Logs365days(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerZhiku(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerZhikuDeclare(dbname)).init();
        (new com.xietong.software.sdtw.db.VolunteerZhikuTeammember(dbname)).init();
        (new com.xietong.software.sdtw.db.BaseDeptCode(dbname)).init();
        (new com.xietong.software.sdtw.db.BaseOrgCode(dbname)).init();
        (new com.xietong.software.sdtw.db.BaseMoudle(dbname)).init();
        (new com.xietong.software.sdtw.db.BaseRoleCode(dbname)).init();
        (new com.xietong.software.sdtw.db.Youthhonour_notice(dbname)).init();
        (new com.xietong.software.sdtw.db.YouthHonour(dbname)).init();
        (new com.xietong.software.sdtw.db.ChuangkuDeclareMembers(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubType(dbname)).init();
        (new com.xietong.software.sdtw.db.Grade(dbname)).init();
        (new com.xietong.software.sdtw.db.InnovationCompetitionMembers(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentsRzd(dbname)).init();
        (new com.xietong.software.sdtw.db.ShortMessage(dbname)).init();
        (new com.xietong.software.sdtw.db.Major(dbname)).init();
        (new com.xietong.software.sdtw.db.Classes(dbname)).init();
        (new com.xietong.software.sdtw.db.Nations(dbname)).init();
        (new com.xietong.software.sdtw.db.BaseOnlineUser(dbname)).init();
        (new com.xietong.software.sdtw.db.BaseUserCode(dbname)).init();
        (new com.xietong.software.sdtw.db.TrainingParticipate(dbname)).init();
        (new com.xietong.software.sdtw.db.ClientAttach(dbname)).init();
        (new com.xietong.software.sdtw.db.Information(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubActivitiesBudgetAmount(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubModifySponsor(dbname)).init();
        (new com.xietong.software.sdtw.db.ClubModifyTeacher(dbname)).init();
        (new com.xietong.software.sdtw.db.Honor(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentRzdState(dbname)).init();
        (new com.xietong.software.sdtw.db.StudentRzd(dbname)).init();
        (new com.xietong.software.sdtw.db.AcademyMoneyNums(dbname)).init();
        (new com.xietong.software.sdtw.db.PracticeDeclareTeam(dbname)).init();
    }
    public static void duplicateSdtw(String source, String target) {
        List cdt = new ArrayList();
        (new com.xietong.software.sdtw.db.Academy(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StandardupGrade(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StandardupGrade_File(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.UserAccounts(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.AddBookGroups(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.AddBookPerson(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Places(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Places_Applytable(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentUnion(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentUnionDept(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentUnionMember(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Club(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubActivities(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubActivityParticipate(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubActivityProject(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubMembers(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubModify(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Club_Regist(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.InnovationCompetition(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.InnovationCompetitionProject(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.InnovationCompetitionAwarditem(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ChuangKu(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ChuangkuDeclare(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.CampusActivity(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.CampusActivityKind(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.CampusParticipate(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubTeacher(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.TrainingArrangement(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerActivity(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerParticipate(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerProject(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerProjectParticipate(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerProjectTeammember(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Practice(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.PracticeDeclare(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.PracticeDeclareTeammember(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.PracticeReport(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Subject(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.SubjectFile(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentClassDuty(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Survey_Basicinfo(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.SurveyAnswer(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.SurveyItems(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Logs365days(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerZhiku(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerZhikuDeclare(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.VolunteerZhikuTeammember(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.BaseDeptCode(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.BaseOrgCode(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.BaseMoudle(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.BaseRoleCode(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Youthhonour_notice(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.YouthHonour(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ChuangkuDeclareMembers(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubType(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Grade(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.InnovationCompetitionMembers(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentsRzd(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ShortMessage(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Major(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Classes(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Nations(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.BaseOnlineUser(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.BaseUserCode(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.TrainingParticipate(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClientAttach(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Information(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubActivitiesBudgetAmount(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubModifySponsor(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.ClubModifyTeacher(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.Honor(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentRzdState(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.StudentRzd(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.AcademyMoneyNums(target)).duplicate(source, cdt);
        (new com.xietong.software.sdtw.db.PracticeDeclareTeam(target)).duplicate(source, cdt);
    }
}
