/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-20 03:44:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.volunteer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xietong.software.util.*;
import com.xietong.software.common.*;
import java.util.*;
import java.io.*;
import java.util.*;
import jxl.*;
import jxl.write.*;
import java.math.BigDecimal;
import com.xietong.software.common.UserInfo;
import com.xietong.software.common.HeadConst;
import com.xietong.software.base.Power;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import com.xietong.software.common.CEditConst;
import com.xietong.software.util.Tool;
import com.xietong.software.sdtw.db.*;

public final class volunteer_002dzhiku_002ddeclare_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/volunteer/pagetop-positionandhelp.jsp", Long.valueOf(1489367536655L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link href=\"../css/common-student.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"../js/tablelist.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\" src=\"../main/js/ajaxfileupload.js\"></script>\r\n");
      out.write("<script src=\"../main/js/common.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".itemname{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
String cmd = ParamUtils.getParameter(request,"cmd",""); 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function form1submit(){\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(form1datacheck()){document.form1.submit();}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function jisuan(){\r\n");
      out.write("\tvar cost1=$(\"#Cost1\").val();\r\n");
      out.write("\tvar cost2=$(\"#Cost2\").val();\r\n");
      out.write("\tvar cost3=$(\"#Cost3\").val();\r\n");
      out.write("\tvar cost4=$(\"#Cost4\").val();\r\n");
      out.write("\tvar cost5=$(\"#Cost5\").val();\r\n");
      out.write("\tvar zongji=Number(cost1)+Number(cost2)+Number(cost3)+Number(cost4)+Number(cost5);\r\n");
      out.write("\t//alert(zongji);\r\n");
      out.write("\t$(\"#Totalcost\").val(zongji);\r\n");
      out.write("}\r\n");
      out.write("function form99cancel(){\r\n");
      out.write("\twindow.location.href=\"volunteer-zhiku-list.jsp\";\r\n");
      out.write("}\r\n");
      out.write("function uploadOtherAttatch(){//上传其他附件\r\n");
      out.write("\t//debugger;\r\n");
      out.write("\tvar name=document.getElementById('OtherAttach').value;\r\n");
      out.write("    $(\"#load1\")\r\n");
      out.write("    .ajaxStart(function(){\r\n");
      out.write("        $(this).show();\r\n");
      out.write("    })\r\n");
      out.write("    .ajaxComplete(function(){\r\n");
      out.write("        $(this).hide();\r\n");
      out.write("    });\r\n");
      out.write("    $.ajaxFileUpload\r\n");
      out.write("    (\r\n");
      out.write("        {\r\n");
      out.write("            url:'VolunteerZhikuDeclareAction.jsp?cmd=otherattach',\r\n");
      out.write("            secureuri:false,\r\n");
      out.write("            fileElementId:'OtherAttach',\r\n");
      out.write("            type:'post',\t\r\n");
      out.write("            dataType: 'json',\r\n");
      out.write("            success: function (data, status)\r\n");
      out.write("            {\r\n");
      out.write("             \t\r\n");
      out.write("                if(typeof(data.error) != 'undefined')\r\n");
      out.write("                {\r\n");
      out.write("                    if(data.error != '')\r\n");
      out.write("                    {                    \r\n");
      out.write("                        alert(data.error);\r\n");
      out.write("                    }else\r\n");
      out.write("                    {\r\n");
      out.write("                    \t//alert(data.ids);\r\n");
      out.write("                    \t// if(document.postForm.AddFileList.value==\"\"){\r\n");
      out.write("                         \tvar be = data.url.indexOf(\"=\");\r\n");
      out.write("                         \tvar en = data.url.lastIndexOf(\"/\");\r\n");
      out.write("                         \tdocument.form1.Addfilelist.value = data.ids;\r\n");
      out.write("                        \r\n");
      out.write("                        /*  }else{\r\n");
      out.write("                         \tvar be = data.url.indexOf(\"=\");\r\n");
      out.write("                         \tvar en = data.url.lastIndexOf(\"/\");\r\n");
      out.write("                         \tdocument.postForm.AddFileList.value += \",\"+data.ids;\r\n");
      out.write("                         }  */\r\n");
      out.write("                         \r\n");
      out.write("                        var table = document.getElementById('ShowFiles');\r\n");
      out.write("                        var num = table.rows.length;\r\n");
      out.write("                        var row = table.insertRow(num);\r\n");
      out.write("                        var filename = data.url.replace(/.*(\\/|\\\\)/, \"\");\r\n");
      out.write("                        filename = data.name;\r\n");
      out.write("                        \r\n");
      out.write("                        var cell = row.insertCell(0);\r\n");
      out.write("                        ");

                        	if(cmd.equals("update")){
                        
      out.write("\r\n");
      out.write("\t\t                        row.id = data.ids;//修改时以防和之前重名\r\n");
      out.write("\t\t                        cell.innerHTML =  '<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/file1.gif\\'/> '+filename+'&nbsp;&nbsp;&nbsp;&nbsp;<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/delete.gif\\' alt=\\'删除\\' title=\\'删除\\' onclick=\\'deleteUpdateFile(\"'+filename+'\",'+data.ids+');\\' style=\"cursor:point;\"/>';\r\n");
      out.write("                        ");

                        	}else{
                        
      out.write("\r\n");
      out.write("\t\t                        row.id = data.ids;//修改时以防和之前重名\r\n");
      out.write("\t\t                        cell.innerHTML =  '<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/file1.gif\\'/> '+filename+'&nbsp;&nbsp;&nbsp;&nbsp;<img src=\\'");
      out.print(HeadConst.apache_url );
      out.write("/main/images/delete.gif\\' alt=\\'删除\\' title=\\'删除\\' onclick=\\'deleteUpdateFile(\"'+filename+'\",'+data.ids+');\\' style=\"cursor:point;\"/>';\r\n");
      out.write("                        ");

                        	}
                        
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function (data, status, e)\r\n");
      out.write("            {\r\n");
      out.write("                alert(\"上传文件失败，请重新上传！\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    )\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("上传文档格式过滤\r\n");
      out.write("*/\r\n");
      out.write("function checkFileType(){//上传文档格式过滤\r\n");
      out.write("\tvar file=document.getElementById('OtherAttach').value;\r\n");
      out.write("\tif(file){\r\n");
      out.write("\t\tvar allowType = {\"doc\":\"\", \"xls\":\"\", \"docx\":\"\", \"xlsx\":\"\"};\r\n");
      out.write("\t\tvar filename=file.replace(/.*(\\/|\\\\)/, \"\");//jquery获得文件名\r\n");
      out.write("\t\tvar fileExt=(/[.]/.exec(filename)) ? /[^.]+$/.exec(filename.toLowerCase()) : '';//jquery获得后缀名\r\n");
      out.write("\t\tif((fileExt+\"\").toLowerCase() in allowType){\r\n");
      out.write("\t\t\tuploadOtherAttatch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\talert(\"上传文件格式不符合要求，请重新选择！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function addItem(){\r\n");
      out.write("\r\n");
      out.write("\topenWindow(\"BaseUserCodeAction.jsp?values=\"+$(\"#SId\").val(),\"703,400\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction setRole(pName,pId){\r\n");
      out.write("\t\t$(\"#teamtable\").append(pName);\r\n");
      out.write("\t\t$(\"#SId\").val(pId);\r\n");
      out.write("\t}\r\n");
      out.write("function deleteUpdateFile(name,id){//删除修改时上传附件\r\n");
      out.write("\tif(confirm('是否确定删除？')){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\t\t\t\r\n");
      out.write("\t\t\turl:\"club-setup-addsave.jsp?cmd=delAttach&did=\"+id,\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tbeforeSend:function(){\r\n");
      out.write("\t\t\t\t$(\"#load1\").show();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(data, status, e){\r\n");
      out.write("\t        \tif(typeof(data.error) != 'undefined'){\r\n");
      out.write("                    if(data.error != '')\r\n");
      out.write("                    {\r\n");
      out.write("                        alert(data.error);\r\n");
      out.write("                    }else\r\n");
      out.write("                    {\r\n");
      out.write("                    \t$(\"#load1\").hide();\r\n");
      out.write("        \t\t\t\tvar row = document.getElementById(id);\r\n");
      out.write("        \t\t\t\tfor(var i=0;i<row.cells.length;i++){\r\n");
      out.write("        \t\t\t\t\trow.deleteCell(i);\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\tvar files = document.form1.AddFileList.value;\r\n");
      out.write("        \t\t\t\t//alert(files+\" \"+id+\" \"+files.indexOf(id))\r\n");
      out.write("        \t\t\t\tif(files.indexOf(id)!=-1){\r\n");
      out.write("        \t\t\t\t\t//替换删掉的附件id\r\n");
      out.write("        \t\t\t\t\tfiles = \",\"+files+\",\";\r\n");
      out.write("        \t\t\t\t\tfiles = files.replace(\",\"+id+\",\",',');\r\n");
      out.write("        \t\t\t\t\t//没有附件的情况\r\n");
      out.write("        \t\t\t\t\tif(files.indexOf(\",\")==files.lastIndexOf(\",\"))\r\n");
      out.write("        \t\t\t\t\t\tfiles = \"\";\r\n");
      out.write("        \t\t\t\t\telse{\r\n");
      out.write("        \t\t\t\t\t\tfiles = files.substring(1,files.length-1);\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\tdocument.form1.AddFileList.value = files;\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("             },\r\n");
      out.write("            error: function (data, status, e){\r\n");
      out.write("            \t$(\"#load1\").hide();\r\n");
      out.write("                alert(\"删除文件失败!\");\r\n");
      out.write("            }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function deleteSponsor(trid,id){\r\n");
      out.write("\t$('#'+trid).remove();\r\n");
      out.write("\tvar files = document.form1.SId.value;\r\n");
      out.write("\t//alert(files+\" \"+id+\" \"+files.indexOf(id))\r\n");
      out.write("\tif(files.indexOf(id)!=-1){\r\n");
      out.write("\t\t//替换删掉的附件id\r\n");
      out.write("\t\tfiles = \",\"+files+\",\";\r\n");
      out.write("\t\tfiles = files.replace(\",\"+id+\",\",',');\r\n");
      out.write("\t\t//没有附件的情况\r\n");
      out.write("\t\tif(files.indexOf(\",\")==files.lastIndexOf(\",\"))\r\n");
      out.write("\t\t\tfiles = \"\";\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tfiles = files.substring(1,files.length-1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.form1.SId.value = files;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");

String ckid=request.getParameter("id");
VolunteerZhikuDeclare vzd=new VolunteerZhikuDeclare();
String useraccount=(String)session.getAttribute("useraccount");

String cd4="";
String cd5="";

UserInfo userinfo=Tool.getUserInfo(request);
if(userinfo==null){
	return;
}

BaseUserCode user=userinfo.getUserCode();


      out.write("\r\n");
      out.write("<body>\r\n");

String strposition = "志愿服务>>山大志库>>";
String strfunction = "申请表";
String strhelpwords = "填写申请表。";

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"location-table\">\r\n");
      out.write("<tr height=\"35\">\r\n");
      out.write("\t<td class=\"location-title\" >您的位置：\r\n");
      out.write("\t\t<span style=\"cursor:pointer;\" onclick=\"showorhide_div('helpdiv')\"></span>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div id=\"helpdiv\" style=\"display:none;\">\r\n");
      out.write("<table \tclass=\"location-help\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("\t<td align=\"left\">系统帮助：</td>\r\n");
      out.write("   \t<td width=\"30\"> \r\n");
      out.write("\t\t<a align=\"right\" href=\"#\" onclick=\"showorhide_div('helpdiv')\"><font face='Webdings' color='#FF0000' style='font- size:32pt'>r</font></a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("\t<td align=\"left\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function showorhide_div(menu){\r\n");
      out.write("    $(\"#\"+menu).toggle();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"command-table\">\r\n");
      out.write("<tr height=\"35px\">\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<a href=\"volunteer-zhiku-list.jsp\">返回</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>    \r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"form1\" method=\"post\" action=\"VolunteerZhikuDeclareAction.jsp?cmd=save1\">\r\n");
      out.write("<table class=\"content-table\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th colspan=\"8\" align=\"left\">“山大志库”项目入库申请表</th> \r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td width=\"27%\" align=\"right\">项目名称</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><input type=\"text\" name=\"Name\" size=\"40\"/></td>\r\n");
      out.write("\t<input type=\"hidden\" name=\"ZhikuId\" size=\"40\" value=\"");
      out.print(ParamUtils.getParameter(request, "zhikuId", ""));
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"AddAccount\" size=\"40\" value=\"");
      out.print(user.getName());
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"Addtime\" size=\"40\" value=\"");
      out.print(new Date());
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"SId\"  id=\"SId\" />\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");

UserInfo userInfo = Tool.getUserInfo(request);
List ZkProjectTypeOptions= CEditConst.getZkProjectTypeOptions(userInfo);
List zhuguanoptions=CEditConst.getAcademyNameOptions(userInfo);

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">团队名称</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><input type=\"text\" name=\"Teamname\" size=\"40\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">所属单位</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\">");
      out.print(HtmlTool.renderSelect(zhuguanoptions, "" + "", "Academy", "-1"));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">项目分组</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.print(HtmlTool.renderSelect(ZkProjectTypeOptions,"", "Type", ""));
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">活动背景及目的</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><textarea name=\"Intention\" cols=\"100\" rows=\"10\" placeholder=\"\"></textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">活动时间安排</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><textarea name=\"Arrange\" cols=\"100\" rows=\"10\" placeholder=\"\"></textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">活动流程</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><textarea name=\"Process\" cols=\"100\" rows=\"10\" placeholder=\"前期准备、活动实施、后期阶段\"></textarea>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">预期成果</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><textarea name=\"Expectresults\" cols=\"100\" rows=\"10\" placeholder=\"\"></textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">已取得成果（选填）</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\"><textarea name=\"Results\" cols=\"100\" rows=\"10\" placeholder=\"\"></textarea></td>\r\n");
      out.write("\t<input type=\"hidden\" name=\"Cost6\" id=\"Cost6\"/>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\"><p>团队组成情况<p/><a href=\"#\" onclick=\"addItem();return false;\">添加</a></td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<table id=\"teamtable\"   style=\"width:100%;font-size:12px;text-align:center;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>学号</td><td >姓名</td><td>学院</td><td>联系方式</td><td>团队分工</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">项目情况</td>\r\n");
      out.write("\t<td align=\"left\" colspan=\"2\">\r\n");
      out.write("\t\t<p><span class=\"itemname\">交通费  </span><input  type=\"number\" id=\"Cost1\" name=\"Cost1\" onblur=\"jisuan()\">仅能输入整数或者小数</p>\r\n");
      out.write("\t\t<p><span class=\"itemname\">住宿费  </span><input type=\"number\"\" id=\"Cost2\"name=\"Cost2\" onblur=\"jisuan()\">仅能输入整数或者小数</p>\r\n");
      out.write("\t\t<p><span class=\"itemname\">其它（请说明）  </span><input type=\"number\"  id=\"Cost3\"name=\"Cost3\" onblur=\"jisuan()\">仅能输入整数或者小数</p>\r\n");
      out.write("\t\t<p><span class=\"itemname\">其它（请说明）  </span><input type=\"number\"id=\"Cost4\" name=\"Cost4\" onblur=\"jisuan()\">仅能输入整数或者小数</p>\r\n");
      out.write("\t\t<p><span class=\"itemname\">其它（请说明）  </span><input type=\"number\" id=\"Cost5\"name=\"Cost5\" onblur=\"jisuan()\">仅能输入整数或者小数</p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<p><span class=\"itemname\">共计  </span><input type=\"text\" name=\"Totalcost\" id=\"Totalcost\" readonly=\"readonly\"></p>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\t\t\t<tr height=\"35\"><td colspan=\"4\" class=\"blocktitle\">附件上传</td></tr>\r\n");
      out.write("<input type=\"hidden\" name=\"Addfilelist\" id=\"Addfilelist\" value=\"");
      out.print(vzd.getAddfilelist());
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"Id\" id=\"Id\"value=\"");
      out.print(vzd.getId());
      out.write("\"/>\r\n");
      out.write("<tr id=\"postFormBookedBooths\">\r\n");
      out.write("\t<td class=\"form_label\"  width=\"14%\" >\r\n");
      out.write("\t<div align=\"right\">相关附件：</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\t<td bgcolor=\"#FFFFFF\" colspan=\"3\" align=\"left\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" id=\"ShowFiles\">\r\n");
      out.write("\t\t\t");

				if(vzd.getId()!=-1){
					ClientAttach ca = new ClientAttach();
					//ca.setDataBase("sdtw");
					String ids = vzd.getAddfilelist();
					if(ids!=null&&ids.trim().length()>0){
						String[] idArray = Tool.split(",",ids);
						for(int i=0;i<idArray.length;i++){
							ClientAttach ca1 = ca.getById(Tool.StrToInt(idArray[i]));
							if(ca1!=null){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr id=\"");
      out.print(ca1.getId() );
      out.write("\"><td><a href=\"");
      out.print(HeadConst.apache_url );
      out.write("/servlet/attach?type=otherattach&id=");
      out.print(ca1.getId() );
      out.write("\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src='");
      out.print(HeadConst.apache_url);
      out.write("/main/images/file1.gif' border=\"0\"/> ");
      out.print(ca1.getUploadName() );
      out.write("</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src='");
      out.print(HeadConst.apache_url);
      out.write("/main/images/delete.gif' alt='删除' title='删除' border=\"0\" onclick=\"javascript:deleteUpdateFile('");
      out.print(ca1.getUploadName());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ca1.getId() );
      out.write("')\" style=\"cursor:point;\"/></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
	}
								}
							}
						}
					
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");
if(vzd.getId()==-1){
      out.write("\r\n");
      out.write("\t\t<input type=\"file\" name=\"OtherAttach\" id=\"OtherAttach\" size=\"40\"/> \r\n");
      out.write("\t\t<input type=\"button\" value=\"上传\" id=\"btn_up\"  onclick=\"checkFileType();\" class=\"formbtn\" style=\"color:black;background-color: #e3e5e8;\"/>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t<img style=\"display:none\" id=\"load1\" src=\"");
      out.print(HeadConst.apache_url);
      out.write("/main/images/loading.gif\"/>\r\n");
      out.write("\t    <div style=\"color:red\">请上传doc、docx、xlsx或xls格式文件，文件最大1M</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th colspan=\"3\">\r\n");
      out.write("\t\t<input class=\"button\" type=\"button\" value=\"提交\" name=\"btn1\" onclick=\"form1submit()\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    \t<input class=\"button\" type=\"button\" value=\"取消\" name=\"btn2\" onclick=\"form99cancel()\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write(" \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function form1datacheck()\r\n");
      out.write("{   \r\n");
      out.write("\t\r\n");
      out.write("\tif (document.form1.Name.value==\"\"){\r\n");
      out.write("\t\talert(\"项目名称不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Name.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.form1.Teamname.value==\"\"){\r\n");
      out.write("\t\talert(\"团队名称不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Teamname.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.form1.Type.value==\"\"){\r\n");
      out.write("\t\talert(\"项目分组不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Type.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.form1.Intention.value==\"\"){\r\n");
      out.write("\t\talert(\"活动背景与目的不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Intention.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.form1.Arrange.value==\"\"){\r\n");
      out.write("\t\talert(\"活动时间安排不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Arrange.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.form1.Process.value==\"\"){\r\n");
      out.write("\t\talert(\"活动流程不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Process.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (document.form1.Expectresults.value==\"\"){\r\n");
      out.write("\t\talert(\"预期成果不能为空！\");\r\n");
      out.write("\t\tdocument.form1.Expectresults.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
