/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-05 06:18:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_002dstudentmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>学生界面头</title>\r\n");
      out.write("<link href=\"css/stumenu.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function js_method(obj){\r\n");
      out.write("\talert(\"请登录系统\");\r\n");
      out.write("}\r\n");
      out.write("/*css无法知道当前屏幕的高度，只能由js获取浏览器的高度-28-120-40-30得到contentFrame的高度*/\r\n");
      out.write("$(function(){\r\n");
      out.write("    var MyHeight=document.documentElement.clientHeight-130;  \r\n");
      out.write("    $(\".contentdiv\").height(MyHeight);\r\n");
      out.write("});  \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"headerbg\">\r\n");
      out.write("<!--导航-->\r\n");
      out.write("<ul id=\"nav\">\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">基本信息</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method(this);\" target=\"contentFrame\">账户信息</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">个人信息</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">组织建设</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href='javascript:js_method();'  target='contentFrame'>五四评比表彰</a></li>\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">培训项目报名</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">培训项目考核</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">结题报告上传</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">学生社团</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">社团成立申请</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">学生社团信息</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">社团活动管理</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">社会工作</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">校学生会</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">院学生会</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">社团工作</a></li>\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">班级工作</a></li>  \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">社会实践</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">项目列表</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">项目申报</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">文化活动</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">主题教育</a></li>\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">文化艺术</a></li>  \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">体育健康</a></li>\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">学术论坛</a></li>  \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">创新创业</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">科技创新</a></li>\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">就业创业</a></li>  \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">创业项目</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">山大创库</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">志愿服务</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">志愿活动浏览</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">志愿竞赛项目</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">志愿信息查询</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">场地信息</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">场地列表</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">场地申请</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">申请状态</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a href=\"#\" class=\"nav-link\">其他服务</a>\r\n");
      out.write("<div class=\"nav-dropdown\" style=\"display: none;\">\r\n");
      out.write("<ul class=\"trending\">\r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">调查问卷</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">团员证补办</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">公告附件上传</a></li> \r\n");
      out.write("<li><a href=\"javascript:js_method();\" target=\"contentFrame\">学生拓展培养认证单</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"contentdiv\">\r\n");
      out.write("\t<iframe class=\"contentFrame\" name=\"contentFrame\" frameborder=\"0\" scrolling=\"auto\" src=\"student-contentFrame.jsp\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("(function(jq){\r\n");
      out.write("\tjq.fn.dropdown = function(settings){\r\n");
      out.write("\tvar defaults = {\r\n");
      out.write("\tdropdownEl: '.dropdown-menu',\r\n");
      out.write("\topenedClass: 'dropdown-open',\r\n");
      out.write("\tdelayTime: 100\r\n");
      out.write("};\r\n");
      out.write("var opts = jq.extend(defaults, settings);\r\n");
      out.write("return this.each(function(){\r\n");
      out.write("\tvar curObj = null;\r\n");
      out.write("\tvar preObj = null;\r\n");
      out.write("\tvar openedTimer = null;\r\n");
      out.write("\tvar closedTimer = null;\r\n");
      out.write("\tjq(this).hover(function(){\r\n");
      out.write("\t\tif(openedTimer)\r\n");
      out.write("\t\t\tclearTimeout(openedTimer);\r\n");
      out.write("\t\tcurObj = jq(this);\r\n");
      out.write("\t\topenedTimer = setTimeout(function(){\r\n");
      out.write("\tcurObj.addClass(opts.openedClass).find(opts.dropdownEl).show();\r\n");
      out.write("},opts.delayTime);\r\n");
      out.write("preObj = curObj;\r\n");
      out.write("},function(){\r\n");
      out.write("if(openedTimer) clearTimeout(openedTimer);\r\n");
      out.write("openedTimer = setTimeout(function(){\r\n");
      out.write("preObj.removeClass(opts.openedClass).find(opts.dropdownEl).hide();\r\n");
      out.write("},opts.delayTime);\r\n");
      out.write("});\r\n");
      out.write("jq(this).bind('click', function(){\r\n");
      out.write("\tif(openedTimer) clearTimeout(openedTimer);\r\n");
      out.write("\topenedTimer = setTimeout(function(){\r\n");
      out.write("\t\tpreObj.removeClass(opts.openedClass).find(opts.dropdownEl).hide();\r\n");
      out.write("\t},opts.delayTime);\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("})(jQuery);\r\n");
      out.write("//下拉菜单\r\n");
      out.write("(function(jq) {\r\n");
      out.write("\tjq('#nav .nav-item').dropdown({dropdownEl:'.nav-dropdown',openedClass:'nav-item-open'});\r\n");
      out.write("})(jQuery);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
