/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-25 06:14:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.chuangku;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.xietong.software.util.*;
import com.xietong.software.common.*;
import java.util.*;
import java.util.ArrayList;
import com.xietong.software.sdtw.db.*;
import com.xietong.software.base.Power;

public final class innovation_002dcompetition_002dproject_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common-student.css\">\r\n");
      out.write("  <script src=\"../js/tablelist.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.min.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

UserInfo userInfo = Tool.getUserInfo(request);
if(!userInfo.hasFunPower(Power.USERSTUDENTPOWER)){
	out.print(HtmlTool.msgBox(request, "请先登录"));
	if (userInfo != null) {
		userInfo.removeCookie(response);
	}
	session.removeAttribute("UserInfo");
	return ;
}
String strposition = "创新创业列表>>创业项目管理";
String strfunction = "创业项目列表";
String strhelpwords = "创业项目列表。";

      out.write("\r\n");
      out.write("<table class=\"location-table\">\r\n");
      out.write("<tr height=\"35\">\r\n");
      out.write("\t<td class=\"location-title\" >您的位置>>创新创业>>创业竞赛列表\r\n");
      out.write("\t\t<span style=\"cursor:pointer;\" onclick=\"showorhide_div('helpdiv')\"></span>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"97%\">\r\n");
      out.write("<tr height=\"25\">\r\n");
      out.write("  <td align=\"right\">\r\n");
      out.write("<!--     <a href=\"innovation-competition-project-xyexport.jsp\" >导出</a> \r\n");
      out.write(" -->  </td>\r\n");
      out.write("</tr>    \r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table class=\"content-table\">\r\n");
      out.write("\r\n");
      out.write("<tr height=\"35\">\r\n");
      out.write("  <th width=\"5%\">序号</th>\r\n");
      out.write("  <th width=\"20%\">项目名称</th>  \r\n");
      out.write("   \r\n");
      out.write("  <th width=\"12%\">负责人</th>\r\n");
      out.write("  <th width=\"15%\">起始时间</th>\r\n");
      out.write("  <th width=\"15%\">截止时间</th>\r\n");
      out.write("  <th colspan=\"3\">操作</th>\r\n");
      out.write("</tr>\r\n");

int pagenumstr=Integer.parseInt(ParamUtils.getParameter(request, "page", "1"));
String istr="", id,projectname="",projectid="",projectleader="",timestart="",timeend="",detailhref="",activitylhref="";
InnovationCompetitionProject icp= new InnovationCompetitionProject();
List cdt= new  ArrayList();
List list= new ArrayList();
cdt.add("order by id desc");
list =icp.query(cdt);
int xuhao=0;
int tiaoshu=list.size();
if(list.size()>0){
	for(int i=0;i<list.size();i++){
		icp=(InnovationCompetitionProject )list.get(i);
xuhao++;
 detailhref="<a href='innovation-competition-project-detail.jsp?id="+icp.getId()+"'>"+icp.getProjectName()+"</a>";
 projectleader=icp.getProjectLeader();
 timestart=icp.getTimeStart() ;
 timeend=icp.getTimeEnd();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr height=\"27\">\r\n");
      out.write("  \t<td  align=\"center\">");
      out.print(xuhao);
      out.write("&nbsp;</td>\r\n");
      out.write("  \t<td  align=\"left\">");
      out.print(detailhref);
      out.write("&nbsp;</td>          \r\n");
      out.write("  \t \r\n");
      out.write("  \t<td  align=\"center\">");
      out.print(projectleader);
      out.write("&nbsp;</td>          \r\n");
      out.write("  \t<td  align=\"center\">");
      out.print(timestart );
      out.write("&nbsp;</td>   \r\n");
      out.write("  \t<td  align=\"center\">");
      out.print(timeend);
      out.write("&nbsp;</td>\r\n");
      out.write("  \t<td colspan=\"3\" align=\"center\"><a href='innovation-competition-list.jsp?proid=");
      out.print(icp.getId());
      out.write("'>查看我的作品</a></td>\r\n");
      out.write("  \t\r\n");
      out.write("</tr>\r\n");


}}
      out.write("\r\n");
      out.write("<tr height=40>\r\n");
      out.write("\t<th width=\"100%\" colspan=\"15\" align=\"center\">\r\n");
      out.write("\t\t共&nbsp");
      out.print(tiaoshu );
      out.write("&nbsp条&nbsp;&nbsp;&nbsp;当前第");
      out.print(pagenumstr );
      out.write("页&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t");

		
		int shangyiye=pagenumstr-1>0?pagenumstr-1:1;
		int xiayiye=pagenumstr*8<tiaoshu?pagenumstr+1:pagenumstr;
		
      out.write("\r\n");
      out.write("   \t\t<a href=\"innovation-competition-project-list.jsp\">首页</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a href=\"innovation-competition-project-list.jsp?page=");
      out.print(shangyiye );
      out.write("\" >上一页</a>  &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"innovation-competition-project-list.jsp?page=");
      out.print(xiayiye);
      out.write("\" >下一页</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    \r\n");
      out.write("\t\t\r\n");
      out.write("\t</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
