/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-26 01:13:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xietong.software.common.UserInfo;
import java.sql.*;
import java.*;
import java.io.*;
import java.util.*;
import jxl.*;
import jxl.write.*;
import java.math.BigDecimal;
import com.xietong.software.sdtw.db.*;
import com.xietong.software.common.HtmlTool;
import com.xietong.software.util.Tool;
import com.xietong.software.common.*;
import com.xietong.software.common.HeadConst;
import com.xietong.software.base.Power;
import com.xietong.software.util.*;
import com.xietong.software.common.*;

public final class bulletin_002dmore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html >\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "jqueryui.jsp", out, true);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\r\n");
      out.write("<link href=\"../css/common-student.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"../js/jquery.min.js\"></script> -->\r\n");
      out.write("<script src=\"../js/tablelist.js\"></script>\r\n");
      out.write("\r\n");
 UserInfo userInfo = Tool.getUserInfo(request); 
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("function showorhide_div(menu)\r\n");
      out.write("{\r\n");
      out.write("    $(\"#\"+menu).toggle();\r\n");
      out.write("}\r\n");
      out.write("function showwinside1(id,title){\r\n");
      out.write("\t//alert(\"2222222222222\");\r\n");
      out.write("\t");
 if(userInfo .hasFunPower(Power.USERSTUDENTPOWER)){
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("parent.parent.showDialog(\"");
      out.print(HeadConst.apache_url);
      out.write("/main/bulletin-detail.jsp?id=\"+id,600,600,title\r\n");
      out.write("\t\t\t,{});\r\n");
      out.write("\t");
}else{
      out.write("\r\n");
      out.write("\tparent.showDialog(\"");
      out.print(HeadConst.apache_url);
      out.write("/main/bulletin-detail.jsp?id=\"+id,600,600,title\r\n");
      out.write("\t\t\t,{});\r\n");
      out.write(" ");
	}
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function zhuandao(){\r\n");
      out.write("\tvar yeshu=$(\"#gopage\").val();\r\n");
      out.write("\twindow.location=\"bulletin-more.jsp?page=\"+yeshu;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table class=\"location-table\" width=\"97%\">\r\n");
      out.write("<tr height=\"35\">\r\n");
      out.write("  <td class=\"location-title\" colspan=\"2\">您的位置：个人消息管理>><span style=\"cursor:hand;\" onclick=\"showorhide_div('helpdiv')\">系统公告</span></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div id=\"helpdiv\" style=\"display:none;\">\r\n");
      out.write("<table class=\"banner-table\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("  <td class=\"menuposword\" width=\"97%\" align=\"left\">系统帮助：</td>\r\n");
      out.write("  <td width=\"5%\" rowspan=\"2\"> \r\n");
      out.write("      <a href=\"#\" onclick=\"showorhide_div('helpdiv')\"><font face='Webdings' color='#FF0000' style='font- size:32pt'>r</font></a>\r\n");
      out.write("  <td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("   <td class=\"bannerword\"align=\"left\">\r\n");
      out.write("        系统公告\r\n");
      out.write("   </td>\r\n");
      out.write("   <td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<table width=\"97%\">\r\n");
      out.write("<tr height=\"25\">\r\n");
      out.write("  <td align=\"right\">\r\n");
      out.write("    <a href=\"sitemsg-list.jsp\">返回</a>\r\n");
      out.write("  </td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table class=\"content-table\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr >\r\n");
      out.write("    <th align=\"center\"  width=\"20%\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;序 号</th>\r\n");
      out.write("    <th align=\"center\"  width=\"\" >标题</th>\r\n");
      out.write("    <th align=\"center\"  width=\"\" >发布用户</th>\r\n");
      out.write("    <th align=\"center\"  width=\"25%\"> 发布时间</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\t");

				
				
				 List list2= new ArrayList();
			       List cdt2=new ArrayList();
			       Information ifo= new Information();
			       BaseUserCode user = new BaseUserCode();
			       int currpage = ParamUtils.getIntParameter(request, "page", 1);
			       currpage=currpage>0?currpage:currpage+1;
			       int start=(currpage-1)*5;
			       Map xy=CEditConst.getAcademyNameMap(userInfo);
			       Map juese=CEditConst.getRoleNameMap(userInfo);
			  	 user=userInfo.getUserCode();
			      String userDept=user.getDeptId()+"";
			    
			      String slist4="";
			      List list4= new ArrayList();
			      Map yonghu=CEditConst.getUserCnNameMap(userInfo);
			     //  Map yonghu2=CEditConst.getUserNameMap(userInfo);
			      //判断是否是团委用户，不是团委用户只能查看团委和本学院的公告
			      if(userInfo.hasFunPower(Power.USERSTUDENTPOWER)){
			    	  String sno=user.getName();
			    	  ClubMembers cbm=new ClubMembers();
			    	  List list3= new ArrayList();
			    	  
				       List cdt3=new ArrayList();
				       cdt3.add("memberSno ='"+sno+"'");
				       list3 =cbm.query( cdt3);
				       
				       //根据学号查学生所参加的社团账号
				       //根据学号查学生所参加的社团账号
				       if(list3.size()>0){
				    	   for(int i=0;i<list3.size();i++){
				    		   cbm=(ClubMembers)list3.get(i);
				    		   //根据社团ID再去查询社团账号
				    		  list4.add("'"+cbm.getMemberClubname()+"'");
				    	   }
				    	   //根据社团id查社团账号
					    	 
					    slist4  =Tool.join(",", list4);
					   
					    	Club club= new Club();
					  	  List list5= new ArrayList();
					    	
					       List cdt5=new ArrayList();
					       List shetuanzhanghao= new ArrayList();
					       cdt5.add("id in ("+slist4+")");
					       list5=club.query(cdt5);
					       if(list5.size()>0){
					    	   for(int i=0;i<list5.size();i++){
					    		   club= (Club)list5.get(i);
					    		   shetuanzhanghao.add("'"+club.getClubId()+"'");
					    	   }
					       }
					       //根据社团账号查社团账号在base表中的id
					       String sshetuanzhanghao=Tool.join(",", shetuanzhanghao);
					       List list6= new ArrayList();
					       List shetuanid= new ArrayList();
					       List cdt6=new ArrayList();
					       cdt6.add("name in ("+sshetuanzhanghao+")");
					       BaseUserCode shetuan= new   BaseUserCode ();
					       list6= shetuan.query(cdt6);
					       if(list6.size()>0){
					    	   for(int i=0;i<list6.size();i++){
					    		  shetuan=(BaseUserCode)list6.get(i) ;
					    		  shetuanid.add(shetuan.getId()+"");
					    	   }
					       }
					    	String sshetuanid=Tool.join(",", shetuanid);
					    	 cdt2.add("UserId in ("+sshetuanid+" )or dept in (1,"+user.getDeptId()+")");
					    	  
					      };
				       }else{
				    	   cdt2.add("dept in (1,"+user.getDeptId()+")");
				       }
			      
			     list2=  ifo.query(cdt2);
			    //如果用户是学生，过滤掉 指导单位与学生是同一部门，但学生并没有参加的社团公告
			    
			     if(userInfo.hasFunPower(Power.USERSTUDENTPOWER)){
				     if(list2.size()>0){
				    	 for(int i = list2.size()-1;i>=0;i--){
				    		 ifo=(Information)list2.get(i);
				    String fabuyonghudanwei=(String)yonghu.get(ifo.getUserId()+"");
				  
			
			
				    BaseUserCode gonggaouser=userInfo.getUserCode(ifo.getUserId());
				   
					if(gonggaouser.getRoles().equals("4")&&!list4.contains("'"+ifo.getUserId()+"'")){
						
						list2.remove(i);
						
					}
				    	 }
				     }
				    	 
				     }
			     int tiaoshu=list2.size();
			     currpage=(currpage-1)*5>tiaoshu?currpage-1:currpage;
			     int end=currpage*5>tiaoshu?tiaoshu:currpage*5;
			     if(list2.size()>0){
			    	 for(int i= start;i<end;i++){
			    		 ifo=(Information)list2.get(i);
			    
			    		
			    		 String fabuyonghuming=(String)yonghu.get(ifo.getUserId()+"");
						    
				
				
      out.write("\r\n");
      out.write("\t\t\t\t <tr >\r\n");
      out.write("        \t\t\t<td >&nbsp;&nbsp;");
      out.print(i+1);
      out.write("</td>\r\n");
      out.write("        \t\t\t<td  align=\"left\"  >\r\n");
      out.write("              \t\t\t<a  title=\"");
      out.print(ifo.getSubject() );
      out.write("\" href=\"\" onclick=\"showwinside1(");
      out.print(ifo.getId());
      out.write(',');
      out.write('\'');
      out.print(ifo.getSubject() );
      out.write("')\" >&nbsp;");
      out.print(ifo.getSubject().length()>30?ifo.getSubject().substring(0, 30)+"..":ifo.getSubject() );
      out.write("</a>\r\n");
      out.write("        \t\t\t</td>\r\n");
      out.write("        \t\t\t<td      >");
      out.print(fabuyonghuming );
      out.write("</td>\r\n");
      out.write("        \t\t\t<td      >");
      out.print(Tool.stringOfCnDate(ifo.getNewDate()));
      out.write("</td>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("  \t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t");
 
					 }
			     }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr height=40>\r\n");
      out.write("    <form name=\"mygo\" method=\"post\" action=\"bulletin-more.jsp?\" target=\"_self\" >\r\n");
      out.write("    <td  width=\"100%\" colspan=\"11\" align=\"center\">一共<font color=\"red\">");
      out.print(tiaoshu );
      out.write("</font>条，每页显示5条\r\n");
      out.write("当前第<font color=\"red\">");
      out.print(currpage );
      out.write("</font>页&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("           <a href=\"bulletin-more.jsp?page=");
      out.print(currpage-1 );
      out.write("\">上一页</a>  &nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("        <a href=\"bulletin-more.jsp?page=");
      out.print(currpage+1 );
      out.write("\">下一页</a>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           <input type=\"text\" name=\"gopage\" id=\"gopage\" value=\"0\" style=\"height:17px;width:20px;\">\r\n");
      out.write("           <input type=\"button\" onclick=\"zhuandao();\" value=\"转到\" >\r\n");
      out.write("    </td>\r\n");
      out.write("    </form>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
