/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-26 01:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.train;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xietong.software.util.ParamUtils;
import com.xietong.software.common.HeadConst;
import com.xietong.software.common.PageControl;
import java.util.HashMap;
import com.xietong.software.sdtw.db.TrainingParticipate;
import java.util.Date;
import java.util.Map;
import com.xietong.software.common.CEditConst;
import com.xietong.software.sdtw.db.TrainingArrangement;
import java.util.List;
import java.util.ArrayList;
import com.xietong.software.sdtw.train.TrainUtil;
import com.xietong.software.common.HtmlTool;
import com.xietong.software.base.Power;
import com.xietong.software.util.Tool;
import com.xietong.software.common.UserInfo;

public final class training_005farrangement_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/train/../student/pagetop-positionandhelp.jsp", Long.valueOf(1493084791070L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

UserInfo userInfo = Tool.getUserInfo(request);
if(!userInfo.hasFunPower(Power.USERSTUDENTPOWER)){
	out.print(HtmlTool.msgBox(request, "请先登录"));
	return ;
}
TrainUtil util = new TrainUtil();
List list = new ArrayList();
list = util.getTrainArrangementList(request);
Map UserCnNameMap = CEditConst.getUserCnNameMap(userInfo);
Map AuditMap = util.getAuditMap();
String currpage = ParamUtils.getParameter(request,"page","1"); 

      out.write("  \r\n");
      out.write("<html >\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common-student.css\">\r\n");
      out.write("<script src='../js/tablelist.js'></script>\r\n");
      out.write("<script src='../js/jquery.min.js'></script>\r\n");
      out.write("<script>\r\n");
      out.write("function addApply(ProjectId,Id,page) {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("        ///sdfz/01src/web\r\n");
      out.write("        url: \"training_arrangement-save.jsp\",\r\n");
      out.write("        data: {\"cmd\":\"addApply\",\"ProjectId\":ProjectId,Id:Id},\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        cache: false,\r\n");
      out.write("        success: function(data){\r\n");
      out.write("                  if(data.msg==\"ok\"){\r\n");
      out.write("                \t  alert(\"报名成功！\")\r\n");
      out.write("                \t  window.location.href='training_arrangement-list.jsp?active=1&page='+page;\r\n");
      out.write("                \t  return;\r\n");
      out.write("                  }\r\n");
      out.write("                  if(data.msg=\"exist\"){\r\n");
      out.write("                \t  alert(\"已报名！\")\r\n");
      out.write("                \t  window.location.href='training_arrangement-list.jsp?active=1&page='+page;\r\n");
      out.write("                \t  return;\r\n");
      out.write("                  }\r\n");
      out.write("                  if(data.meg==\"error\"){\r\n");
      out.write("                \t  alert(\"申请失败，请重新申请！\");\r\n");
      out.write("                \t  window.location.href='training_arrangement-list.jsp?active=1&page='+page;\r\n");
      out.write("                \t  return;\r\n");
      out.write("                  }\r\n");
      out.write("                 },\r\n");
      out.write("                 error : function() { \r\n");
      out.write("                             alert( \"异常！\"); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function AddWorkAndReportFile(Id,page){\r\n");
      out.write("\tlocation = \"learn-arrange-work.jsp?Id=\"+Id+\"&page=\"+page;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
 
	String strposition = "团校培训管理>>培训项目报名>>";
	String strfunction = "学习项目列表";
	String strhelpwords = "展示学习项目的列表，点击项目名称上时可以显示相应项目说明。";
	

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"location-table\" >\r\n");
      out.write("<tr height=\"35\">\r\n");
      out.write("\t<td class=\"location-title\" >您的位置：");
      out.print(strposition );
      out.write("\r\n");
      out.write("\t\t<span style=\"cursor:pointer;\" onclick=\"showorhide_div('helpdiv')\">");
      out.print(strfunction );
      out.write("</span>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div id=\"helpdiv\" style=\"display:none;width:89%;margin:0 auto;\">\r\n");
      out.write("<table \tclass=\"location-help\"  cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("\t<td align=\"left\">系统帮助：</td>\r\n");
      out.write("   \t<td width=\"30\"> \r\n");
      out.write("\t\t<a align=\"right\" href=\"#\" onclick=\"showorhide_div('helpdiv')\"><font face='Webdings' color='#FF0000' style='font- size:32pt'>×</font></a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"20\">\r\n");
      out.write("\t<td align=\"left\">");
      out.print(strhelpwords );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function showorhide_div(menu){\r\n");
      out.write("    $(\"#\"+menu).toggle();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"content-table\">\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"5%\">序号</th>\r\n");
      out.write("\t\t<th width=\"30%\">学习项目</th>\r\n");
      out.write("\t\t<th width=\"20%\">时间安排</th>\r\n");
      out.write("\t\t<th width=\"20%\">负责人</th>\r\n");
      out.write("\t\t<th width=\"15%\">审核状态</th>\r\n");
      out.write("\t\t<th>操作</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

	Map<String,TrainingParticipate> map = new HashMap<String,TrainingParticipate> ();
	map = util.getTrainingParticipateMap(userInfo.getId());
	if (list.size()>0) {
		for (int i=0;i<list.size();i++) {
			TrainingArrangement v = new TrainingArrangement();
			v = (TrainingArrangement)list.get(i);
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>");
      out.print(i+1 );
      out.write("</td>\r\n");
      out.write("\t\t<td><a href=\"training_arrangement-detail.jsp?id=");
      out.print(v.getId());
      out.write("&page=");
      out.print(currpage );
      out.write('"');
      out.write('>');
      out.print(v.getProjectName() );
      out.write("</a></td>\r\n");
      out.write("\t\t<td>");
      out.print(Tool.stringOfDate(v.getStartTime()));
      out.write('~');
      out.print(Tool.stringOfDate(v.getEndTime()));
      out.write("</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");
      out.print(v.getHostName() );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");

		if (map.get(v.getId()+"")!=null) {
			TrainingParticipate item = new TrainingParticipate();
			item = map.get(v.getId()+"");
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(AuditMap.get(item.getAudit()) );
      out.write("\r\n");
      out.write("\t\t");
}
		
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");

		if (v.getStartTime().getTime()<=new Date().getTime()&&v.getEndTime().getTime()>=new Date().getTime()) {
			if (map.get(v.getId()+"")!=null) {
				TrainingParticipate item = new TrainingParticipate();
				item = map.get(v.getId()+"");
      out.write("\r\n");
      out.write("\t\t\t\t");
if (item.getAudit()==-1) {
      out.write("\r\n");
      out.write("\t\t\t\t&nbsp;<a href=\"training_arrangement-detail.jsp?id=");
      out.print(v.getId());
      out.write("&page=");
      out.print(currpage );
      out.write("\">已报名</a>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:;\"\tonclick=\"AddWorkAndReportFile(");
      out.print(item.getId());
      out.write(',');
      out.print(currpage );
      out.write(")\">\r\n");
      out.write("\t\t\t\t");

				if (item.getAudit()==0){
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;可上传作业\r\n");
      out.write("\t\t\t\t");
}
				if (item.getAudit()==2) {
      out.write("\r\n");
      out.write("\t\t\t\t\t&nbsp;可上传结题报告\r\n");
      out.write("\t\t\t\t");
}
				
      out.write("\r\n");
      out.write("\t\t\t\t</a> \r\n");
      out.write("\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"javascript:;\"\tonclick=\"addApply(");
      out.print(v.getId());
      out.write(',');
      out.print(currpage );
      out.write(")\">申请参加</a> \r\n");
      out.write("\t\t\t");
}
		
      out.write("\r\n");
      out.write("\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t已过期\r\n");
      out.write("\t\t");
}
		
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t");

		}
	}
	AuditMap.clear();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");

	PageControl pagecontrol = (PageControl)request.getAttribute("PageControl");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(pagecontrol.getControl_win8_("training_arrangement-list.jsp",  HeadConst.apache_url+"/main/images/skin/"+userInfo.getSkinId()));
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
