/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-04-26 08:20:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.stuUnion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xietong.software.sdtw.db.StudentUnionMember;
import com.xietong.software.sdtw.db.StudentUnionDept;
import java.sql.*;
import java.util.*;
import com.xietong.software.util.*;
import com.xietong.software.common.*;
import java.util.*;
import com.xietong.software.base.Power;

public final class stuorg_002dstudentunion_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body,html{\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("}\r\n");
      out.write(".minfo{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\twidth:60px;\r\n");
      out.write("}\r\n");
      out.write(".xinfo{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

UserInfo userinfo = Tool.getUserInfo(request);
if(!userinfo.hasFunPower(Power.USERSTUDENTPOWER)){
	out.print(HtmlTool.msgBox(request, "请先登录"));
	if (userinfo != null) {
		userinfo.removeCookie(response);
	}
	session.removeAttribute("UserInfo");
	return ;
}
String space4="&nbsp;&nbsp;&nbsp;&nbsp;";
UserInfo userInfo = Tool.getUserInfo(request);
Map cnnamemap=CEditConst.getUserCnNameMap(userInfo);

String[] unionnamearry={"校学生会","校研究生会","院学生会","院研究生会"};

String deptname="",principal="",contact="",listorder="",deptprofile="",functionstr="",addfilelist = "",addtime="",addaccount="";
int  id =ParamUtils.getIntParameter(request, "Id", 1);
StudentUnionDept  sud=new StudentUnionDept();
List list= new ArrayList();
List cdt= new ArrayList();
cdt.add("id="+id);
list =sud.query(cdt);
if(list.size()>0){
	sud=(StudentUnionDept)list.get(0);
	deptname=sud.getDeptName();
	if(sud.getAddaccount()!=""){
	principal=(String)cnnamemap.get(sud.getAddaccount()+"");}
	contact=sud.getContact();
	deptprofile=sud.getDeptprofile()==null?"":sud.getDeptprofile();
	functionstr=sud.getFunctionstr();
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"../css/common-student.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"../js/tablelist.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table class=\"content-table\" style=\"width:100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td width=\"25%\" align=\"right\">部门名称：</td>\r\n");
      out.write("\t<td align=\"left\"><strong>");
      out.print(deptname);
      out.write("</strong></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align=\"right\">负责人：</td>\r\n");
      out.write(" \t<td align=\"left\">");
      out.print(principal);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   \t<td align=\"right\">联系方式：</td>\r\n");
      out.write("   \t<td align=\"left\">");
      out.print(contact);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("   \t<td align=\"right\">部门简介：</td>\r\n");
      out.write("   \t<td align=\"left\">");
      out.print(deptprofile);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   \t<td align=\"right\">主要职能：</td>\r\n");
      out.write("   \t<td align=\"left\">");
      out.print(functionstr);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   \t<td align=\"right\">主要成员：</td>\r\n");
      out.write("   \t<td align=\"left\">\r\n");

String sno = "",sname = "",sacademy="",grade="",campus="",ssex="",duty = "",phone="",remark = "";   	
StudentUnionMember sum= new  StudentUnionMember ();
Map dutymap=CEditConst.getStuDutyMap(userInfo);
Map xynamemap= CEditConst.getAcademyNameMap(userInfo);
Map nianjimap= CEditConst.getGradeNameMap(userInfo);
Map orgname=CEditConst.getOrgCityNameMap(userInfo);
List list1= new ArrayList();
List cdt1= new ArrayList();
cdt1.add("deptid="+id);
list1=sum.query(cdt1);
if(list1.size()>0){
	for(int i=0;i<list1.size();i++){
	sum=(StudentUnionMember)list1.get(i);
	duty=(String)dutymap.get(sum.getDuty()+"")==null?"":(String)dutymap.get(sum.getDuty()+"");
	sname=sum.getSNo();
	grade=(String)nianjimap.get(sum.getSchoolYear())==null?"":(String)nianjimap.get(sum.getSchoolYear());
	phone=sum.getPhone();
	sacademy=(String)xynamemap.get(sum.getChargeDept())==null?"":(String)xynamemap.get(sum.getChargeDept());
	remark=sum.getRemark();
	if(sum.getCampus()!=""){
	campus=(String)orgname.get(sum.getCampus())==null?"":(String)orgname.get(sum.getCampus());
	}

      out.write("\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span class=\"minfo\">");
      out.print(duty);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"minfo\">");
      out.print(sname);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"minfo\">");
      out.print(ssex);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"xinfo\">");
      out.print(sacademy);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"minfo\">");
      out.print(grade);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"xinfo\">");
      out.print(campus);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"xinfo\">");
      out.print(phone);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"xinfo\">");
      out.print(remark);
      out.write("</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
}} 
      out.write("\t\t\t\r\n");
      out.write("   \t\r\n");
      out.write("   \t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   \t<td align=\"right\">附件资料：</td>\r\n");
      out.write("   \t<td align=\"left\">\r\n");

if(addfilelist!=""){
	String[] addfilelistarry=addfilelist.split("\10");
	for(int i=0;i<addfilelistarry.length;i++){
		String[] filestr=addfilelistarry[i].split("\20");

      out.write("\r\n");
      out.write("\t\t<p><a href=\"../datafile/stuorg/");
      out.print(filestr[3] );
      out.write('"');
      out.write('>');
      out.print(filestr[1]);
      out.write('(');
      out.print(filestr[2]);
      out.write(")</a></p>\r\n");

	}
}else{

      out.write("\r\n");
      out.write("\t\t无附件资料\r\n");
	
}

      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t <td  align=\"right\">添加时间：</td>\r\n");
      out.write("\t <td align=\"left\">");
      out.print(addtime);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
